//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentData
    {
        public int ResourceId { get; set; }
        public string ResourceFirstName { get; set; }
        public string ResourceLastName { get; set; }
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public short Year { get; set; }
        public byte Month { get; set; }
        public Nullable<decimal> FteClient { get; set; }
        public Nullable<decimal> FteReal { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
    }
}
