//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assignment()
        {
            this.AssignmentPeriod = new HashSet<AssignmentPeriod>();
        }
    
        public int AssignmentId { get; set; }
        public int ProjectId { get; set; }
        public int ResourceId { get; set; }
        public string BillingCountry { get; set; }
        public string Sponsor { get; set; }
        public string Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentPeriod> AssignmentPeriod { get; set; }
        public virtual Project Project { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
