//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int Id { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Level { get; set; }
        public string Type { get; set; }
        public string Trace { get; set; }
        public string Message { get; set; }
        public Nullable<int> Line { get; set; }
        public string Filename { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
