//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.AssignmentPeriod = new HashSet<AssignmentPeriod>();
            this.Po = new HashSet<Po>();
            this.Attachment = new HashSet<Attachment>();
        }
    
        public int InvoiceId { get; set; }
        public int ClientId { get; set; }
        public string InvoiceNumber { get; set; }
        public byte TypeId { get; set; }
        public decimal Amount { get; set; }
        public string CurrencyId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Comments { get; set; }
        public System.DateTime InvoiceDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual InvoiceType InvoiceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentPeriod> AssignmentPeriod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Po> Po { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachment { get; set; }
    }
}
