//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TFSM_PortalCotizadorEntities : DbContext
    {
        public TFSM_PortalCotizadorEntities()
            : base("name=TFSM_PortalCotizadorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_perfilador_C_Preguntas> tbl_perfilador_C_Preguntas { get; set; }
        public virtual DbSet<tbl_perfilador_Destinos> tbl_perfilador_Destinos { get; set; }
        public virtual DbSet<paso_portal_C_Aseguradora> paso_portal_C_Aseguradora { get; set; }
        public virtual DbSet<paso_portal_C_Auto> paso_portal_C_Auto { get; set; }
        public virtual DbSet<paso_portal_C_Coberturas> paso_portal_C_Coberturas { get; set; }
        public virtual DbSet<paso_portal_C_DescEstados> paso_portal_C_DescEstados { get; set; }
        public virtual DbSet<paso_portal_C_Estados> paso_portal_C_Estados { get; set; }
        public virtual DbSet<paso_portal_C_Modelos> paso_portal_C_Modelos { get; set; }
        public virtual DbSet<paso_portal_C_PlazoAseguradora> paso_portal_C_PlazoAseguradora { get; set; }
        public virtual DbSet<paso_portal_C_Plazos> paso_portal_C_Plazos { get; set; }
        public virtual DbSet<paso_portal_C_Tipo> paso_portal_C_Tipo { get; set; }
        public virtual DbSet<tbl_cotizador_estados> tbl_cotizador_estados { get; set; }
        public virtual DbSet<tbl_cotizador_paises> tbl_cotizador_paises { get; set; }
        public virtual DbSet<tbl_perfilador_Respuestas> tbl_perfilador_Respuestas { get; set; }
        public virtual DbSet<tbl_portal_C_Aseguradora> tbl_portal_C_Aseguradora { get; set; }
        public virtual DbSet<tbl_portal_C_Auto> tbl_portal_C_Auto { get; set; }
        public virtual DbSet<tbl_portal_C_Coberturas> tbl_portal_C_Coberturas { get; set; }
        public virtual DbSet<tbl_portal_C_CoeficienteAnualidad> tbl_portal_C_CoeficienteAnualidad { get; set; }
        public virtual DbSet<tbl_portal_C_DescEstados> tbl_portal_C_DescEstados { get; set; }
        public virtual DbSet<tbl_portal_C_DescEstados_V> tbl_portal_C_DescEstados_V { get; set; }
        public virtual DbSet<tbl_portal_C_Estados> tbl_portal_C_Estados { get; set; }
        public virtual DbSet<tbl_portal_C_Modelos> tbl_portal_C_Modelos { get; set; }
        public virtual DbSet<tbl_portal_C_plan> tbl_portal_C_plan { get; set; }
        public virtual DbSet<tbl_portal_C_PlazoAseguradora> tbl_portal_C_PlazoAseguradora { get; set; }
        public virtual DbSet<tbl_portal_C_Plazos> tbl_portal_C_Plazos { get; set; }
        public virtual DbSet<tbl_portal_C_Tipo> tbl_portal_C_Tipo { get; set; }
        public virtual DbSet<tbl_portal_C_tipo_persona> tbl_portal_C_tipo_persona { get; set; }
        public virtual DbSet<tbl_portal_C_TipoUso> tbl_portal_C_TipoUso { get; set; }
        public virtual DbSet<tbl_portal_Distribuidores> tbl_portal_Distribuidores { get; set; }
        public virtual DbSet<tbl_portal_Llaves> tbl_portal_Llaves { get; set; }
        public virtual DbSet<tbl_portal_parametros> tbl_portal_parametros { get; set; }
    
        public virtual ObjectResult<sp_costo_total_seguro_Result> sp_costo_total_seguro(string estado, string aseguradora, string cobertura, string auto, string tipo, string modelo, string tipo_Uso, string pagoInicial, string plazo)
        {
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var aseguradoraParameter = aseguradora != null ?
                new ObjectParameter("Aseguradora", aseguradora) :
                new ObjectParameter("Aseguradora", typeof(string));
    
            var coberturaParameter = cobertura != null ?
                new ObjectParameter("Cobertura", cobertura) :
                new ObjectParameter("Cobertura", typeof(string));
    
            var autoParameter = auto != null ?
                new ObjectParameter("Auto", auto) :
                new ObjectParameter("Auto", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            var modeloParameter = modelo != null ?
                new ObjectParameter("Modelo", modelo) :
                new ObjectParameter("Modelo", typeof(string));
    
            var tipo_UsoParameter = tipo_Uso != null ?
                new ObjectParameter("Tipo_Uso", tipo_Uso) :
                new ObjectParameter("Tipo_Uso", typeof(string));
    
            var pagoInicialParameter = pagoInicial != null ?
                new ObjectParameter("PagoInicial", pagoInicial) :
                new ObjectParameter("PagoInicial", typeof(string));
    
            var plazoParameter = plazo != null ?
                new ObjectParameter("Plazo", plazo) :
                new ObjectParameter("Plazo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_costo_total_seguro_Result>("sp_costo_total_seguro", estadoParameter, aseguradoraParameter, coberturaParameter, autoParameter, tipoParameter, modeloParameter, tipo_UsoParameter, pagoInicialParameter, plazoParameter);
        }
    
        public virtual int sp_actualiza_catalogos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_actualiza_catalogos");
        }
    
        public virtual int sp_actualiza_catalogos_portal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_actualiza_catalogos_portal");
        }
    
        public virtual int sp_llena_C_DescEstados_V()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_llena_C_DescEstados_V");
        }
    }
}
