//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DxcSitefinityToyotaEntities : DbContext
    {
        public DxcSitefinityToyotaEntities()
            : base("name=DxcSitefinityToyotaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sf_media_content> sf_media_content { get; set; }
        public virtual DbSet<ActionLog> ActionLog { get; set; }
        public virtual DbSet<Assignment> Assignment { get; set; }
        public virtual DbSet<AssignmentPeriod> AssignmentPeriod { get; set; }
        public virtual DbSet<Attachment> Attachment { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<ContactType> ContactType { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<ErrorLog> ErrorLog { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<InvoiceType> InvoiceType { get; set; }
        public virtual DbSet<OAConflicts> OAConflicts { get; set; }
        public virtual DbSet<OAImportConfigurations> OAImportConfigurations { get; set; }
        public virtual DbSet<oakeygen> oakeygen { get; set; }
        public virtual DbSet<OASyncImportSummary> OASyncImportSummary { get; set; }
        public virtual DbSet<OASyncListSummary> OASyncListSummary { get; set; }
        public virtual DbSet<OASyncLog> OASyncLog { get; set; }
        public virtual DbSet<Po> Po { get; set; }
        public virtual DbSet<PoVersion> PoVersion { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<ProjectContact> ProjectContact { get; set; }
        public virtual DbSet<ProjectState> ProjectState { get; set; }
        public virtual DbSet<ProjectType> ProjectType { get; set; }
        public virtual DbSet<RedmineActivity> RedmineActivity { get; set; }
        public virtual DbSet<Resource> Resource { get; set; }
        public virtual DbSet<ResourceType> ResourceType { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sf_ab_campaign> sf_ab_campaign { get; set; }
        public virtual DbSet<sf_ab_test> sf_ab_test { get; set; }
        public virtual DbSet<sf_ab_test_goal> sf_ab_test_goal { get; set; }
        public virtual DbSet<sf_ab_test_variation> sf_ab_test_variation { get; set; }
        public virtual DbSet<sf_addresses> sf_addresses { get; set; }
        public virtual DbSet<sf_app_setting> sf_app_setting { get; set; }
        public virtual DbSet<sf_approval_tracking_record> sf_approval_tracking_record { get; set; }
        public virtual DbSet<sf_blg_psts_pblshd_trnslations> sf_blg_psts_pblshd_trnslations { get; set; }
        public virtual DbSet<sf_blog_posts> sf_blog_posts { get; set; }
        public virtual DbSet<sf_blog_posts_category> sf_blog_posts_category { get; set; }
        public virtual DbSet<sf_blog_posts_sf_commnt> sf_blog_posts_sf_commnt { get; set; }
        public virtual DbSet<sf_blog_posts_sf_language_data> sf_blog_posts_sf_language_data { get; set; }
        public virtual DbSet<sf_blog_posts_tags> sf_blog_posts_tags { get; set; }
        public virtual DbSet<sf_blogs> sf_blogs { get; set; }
        public virtual DbSet<sf_blogs_sf_commnt> sf_blogs_sf_commnt { get; set; }
        public virtual DbSet<sf_bounce_stat> sf_bounce_stat { get; set; }
        public virtual DbSet<sf_calendars> sf_calendars { get; set; }
        public virtual DbSet<sf_campaign> sf_campaign { get; set; }
        public virtual DbSet<sf_campaign_link> sf_campaign_link { get; set; }
        public virtual DbSet<sf_campaign_sf_campaign_link> sf_campaign_sf_campaign_link { get; set; }
        public virtual DbSet<sf_chunks> sf_chunks { get; set; }
        public virtual DbSet<sf_cnt_location_filters> sf_cnt_location_filters { get; set; }
        public virtual DbSet<sf_cnt_locations> sf_cnt_locations { get; set; }
        public virtual DbSet<sf_cntnt_tems_sf_language_data> sf_cntnt_tems_sf_language_data { get; set; }
        public virtual DbSet<sf_cntnt_tms_pblshd_trnsltions> sf_cntnt_tms_pblshd_trnsltions { get; set; }
        public virtual DbSet<sf_commnt> sf_commnt { get; set; }
        public virtual DbSet<sf_commnt_parent_group_ids> sf_commnt_parent_group_ids { get; set; }
        public virtual DbSet<sf_commnt_sf_commnt> sf_commnt_sf_commnt { get; set; }
        public virtual DbSet<sf_config_variables> sf_config_variables { get; set; }
        public virtual DbSet<sf_content_items> sf_content_items { get; set; }
        public virtual DbSet<sf_content_items_category> sf_content_items_category { get; set; }
        public virtual DbSet<sf_content_items_sf_commnt> sf_content_items_sf_commnt { get; set; }
        public virtual DbSet<sf_content_items_tags> sf_content_items_tags { get; set; }
        public virtual DbSet<sf_content_link> sf_content_link { get; set; }
        public virtual DbSet<sf_content_link_attrbutes> sf_content_link_attrbutes { get; set; }
        public virtual DbSet<sf_content_relation> sf_content_relation { get; set; }
        public virtual DbSet<sf_control_properties> sf_control_properties { get; set; }
        public virtual DbSet<sf_counters> sf_counters { get; set; }
        public virtual DbSet<sf_cs_comments> sf_cs_comments { get; set; }
        public virtual DbSet<sf_cs_groups> sf_cs_groups { get; set; }
        public virtual DbSet<sf_cs_threads> sf_cs_threads { get; set; }
        public virtual DbSet<sf_dashboard_log> sf_dashboard_log { get; set; }
        public virtual DbSet<sf_dashboard_watchlist> sf_dashboard_watchlist { get; set; }
        public virtual DbSet<sf_delivery_entry> sf_delivery_entry { get; set; }
        public virtual DbSet<sf_draft_pages> sf_draft_pages { get; set; }
        public virtual DbSet<sf_drft_pages_sf_language_data> sf_drft_pages_sf_language_data { get; set; }
        public virtual DbSet<sf_dynamic_content> sf_dynamic_content { get; set; }
        public virtual DbSet<sf_dynamic_list> sf_dynamic_list { get; set; }
        public virtual DbSet<sf_dynamic_type_base> sf_dynamic_type_base { get; set; }
        public virtual DbSet<sf_dynmc_cntnt_pblshd_trnsltns> sf_dynmc_cntnt_pblshd_trnsltns { get; set; }
        public virtual DbSet<sf_dynmc_cntnt_sf_lnguage_data> sf_dynmc_cntnt_sf_lnguage_data { get; set; }
        public virtual DbSet<sf_ec_customer_profile> sf_ec_customer_profile { get; set; }
        public virtual DbSet<sf_events> sf_events { get; set; }
        public virtual DbSet<sf_events_category> sf_events_category { get; set; }
        public virtual DbSet<sf_events_sf_commnt> sf_events_sf_commnt { get; set; }
        public virtual DbSet<sf_events_sf_language_data> sf_events_sf_language_data { get; set; }
        public virtual DbSet<sf_events_tags> sf_events_tags { get; set; }
        public virtual DbSet<sf_failed_deliveries> sf_failed_deliveries { get; set; }
        public virtual DbSet<sf_files_monitor_data> sf_files_monitor_data { get; set; }
        public virtual DbSet<sf_folders> sf_folders { get; set; }
        public virtual DbSet<sf_form_description> sf_form_description { get; set; }
        public virtual DbSet<sf_form_description_attrbutes> sf_form_description_attrbutes { get; set; }
        public virtual DbSet<sf_form_description_category> sf_form_description_category { get; set; }
        public virtual DbSet<sf_form_description_sf_commnt> sf_form_description_sf_commnt { get; set; }
        public virtual DbSet<sf_form_description_tags> sf_form_description_tags { get; set; }
        public virtual DbSet<sf_form_entry> sf_form_entry { get; set; }
        public virtual DbSet<sf_forum_groups> sf_forum_groups { get; set; }
        public virtual DbSet<sf_forum_posts> sf_forum_posts { get; set; }
        public virtual DbSet<sf_forum_threads> sf_forum_threads { get; set; }
        public virtual DbSet<sf_forums> sf_forums { get; set; }
        public virtual DbSet<sf_frm_dscrptn_pblshd_trnsltns> sf_frm_dscrptn_pblshd_trnsltns { get; set; }
        public virtual DbSet<sf_frm_dscrptn_sf_lnguage_data> sf_frm_dscrptn_sf_lnguage_data { get; set; }
        public virtual DbSet<sf_frm_dscrptn_sf_prsnttn_data> sf_frm_dscrptn_sf_prsnttn_data { get; set; }
        public virtual DbSet<sf_idsrv_claims> sf_idsrv_claims { get; set; }
        public virtual DbSet<sf_idsrv_consents> sf_idsrv_consents { get; set; }
        public virtual DbSet<sf_idsrv_keys> sf_idsrv_keys { get; set; }
        public virtual DbSet<sf_idsrv_tokens> sf_idsrv_tokens { get; set; }
        public virtual DbSet<sf_issue_subscriber_report> sf_issue_subscriber_report { get; set; }
        public virtual DbSet<sf_language_data> sf_language_data { get; set; }
        public virtual DbSet<sf_lbraries_thumbnail_profiles> sf_lbraries_thumbnail_profiles { get; set; }
        public virtual DbSet<sf_libraries> sf_libraries { get; set; }
        public virtual DbSet<sf_libraries_sf_commnt> sf_libraries_sf_commnt { get; set; }
        public virtual DbSet<sf_lic_user_activity> sf_lic_user_activity { get; set; }
        public virtual DbSet<sf_link_click_stat> sf_link_click_stat { get; set; }
        public virtual DbSet<sf_list_items> sf_list_items { get; set; }
        public virtual DbSet<sf_list_items_category> sf_list_items_category { get; set; }
        public virtual DbSet<sf_list_items_sf_commnt> sf_list_items_sf_commnt { get; set; }
        public virtual DbSet<sf_list_items_sf_language_data> sf_list_items_sf_language_data { get; set; }
        public virtual DbSet<sf_list_items_tags> sf_list_items_tags { get; set; }
        public virtual DbSet<sf_lists> sf_lists { get; set; }
        public virtual DbSet<sf_lists_sf_commnt> sf_lists_sf_commnt { get; set; }
        public virtual DbSet<sf_locks> sf_locks { get; set; }
        public virtual DbSet<sf_lst> sf_lst { get; set; }
        public virtual DbSet<sf_lst_tms_pblshd_translations> sf_lst_tms_pblshd_translations { get; set; }
        public virtual DbSet<sf_manager_info> sf_manager_info { get; set; }
        public virtual DbSet<sf_mb_dnc_cnt_provider> sf_mb_dnc_cnt_provider { get; set; }
        public virtual DbSet<sf_mb_dynamic_module> sf_mb_dynamic_module { get; set; }
        public virtual DbSet<sf_mb_dynamic_module_field> sf_mb_dynamic_module_field { get; set; }
        public virtual DbSet<sf_mb_dynamic_module_type> sf_mb_dynamic_module_type { get; set; }
        public virtual DbSet<sf_mb_fields_backend_section> sf_mb_fields_backend_section { get; set; }
        public virtual DbSet<sf_mbl_frmt_cntnt_types> sf_mbl_frmt_cntnt_types { get; set; }
        public virtual DbSet<sf_mbl_frmt_dfntns> sf_mbl_frmt_dfntns { get; set; }
        public virtual DbSet<sf_mbl_frmt_templates> sf_mbl_frmt_templates { get; set; }
        public virtual DbSet<sf_md_cntnt_pblshd_trnslations> sf_md_cntnt_pblshd_trnslations { get; set; }
        public virtual DbSet<sf_md_content_sf_language_data> sf_md_content_sf_language_data { get; set; }
        public virtual DbSet<sf_media_content_category> sf_media_content_category { get; set; }
        public virtual DbSet<sf_media_content_category2> sf_media_content_category2 { get; set; }
        public virtual DbSet<sf_media_content_category3> sf_media_content_category3 { get; set; }
        public virtual DbSet<sf_media_content_sf_commnt> sf_media_content_sf_commnt { get; set; }
        public virtual DbSet<sf_media_content_tags> sf_media_content_tags { get; set; }
        public virtual DbSet<sf_media_content_tags2> sf_media_content_tags2 { get; set; }
        public virtual DbSet<sf_media_content_tags3> sf_media_content_tags3 { get; set; }
        public virtual DbSet<sf_media_file_links> sf_media_file_links { get; set; }
        public virtual DbSet<sf_media_file_urls> sf_media_file_urls { get; set; }
        public virtual DbSet<sf_media_thumbnails> sf_media_thumbnails { get; set; }
        public virtual DbSet<sf_message_body> sf_message_body { get; set; }
        public virtual DbSet<sf_meta_attribute> sf_meta_attribute { get; set; }
        public virtual DbSet<sf_meta_data_mapping> sf_meta_data_mapping { get; set; }
        public virtual DbSet<sf_meta_fields> sf_meta_fields { get; set; }
        public virtual DbSet<sf_meta_index> sf_meta_index { get; set; }
        public virtual DbSet<sf_meta_index_composite_fields> sf_meta_index_composite_fields { get; set; }
        public virtual DbSet<sf_meta_type_descriptions> sf_meta_type_descriptions { get; set; }
        public virtual DbSet<sf_meta_types> sf_meta_types { get; set; }
        public virtual DbSet<sf_meta_types_section_names> sf_meta_types_section_names { get; set; }
        public virtual DbSet<sf_module_vrsn> sf_module_vrsn { get; set; }
        public virtual DbSet<sf_news_items> sf_news_items { get; set; }
        public virtual DbSet<sf_news_items_category> sf_news_items_category { get; set; }
        public virtual DbSet<sf_news_items_sf_commnt> sf_news_items_sf_commnt { get; set; }
        public virtual DbSet<sf_news_items_sf_language_data> sf_news_items_sf_language_data { get; set; }
        public virtual DbSet<sf_news_items_tags> sf_news_items_tags { get; set; }
        public virtual DbSet<sf_notif_cmplt_msg_job> sf_notif_cmplt_msg_job { get; set; }
        public virtual DbSet<sf_notif_msg_job> sf_notif_msg_job { get; set; }
        public virtual DbSet<sf_notif_msg_job_log> sf_notif_msg_job_log { get; set; }
        public virtual DbSet<sf_notif_msg_template> sf_notif_msg_template { get; set; }
        public virtual DbSet<sf_notif_subscr_list> sf_notif_subscr_list { get; set; }
        public virtual DbSet<sf_notif_subscribers> sf_notif_subscribers { get; set; }
        public virtual DbSet<sf_notif_subscriptions> sf_notif_subscriptions { get; set; }
        public virtual DbSet<sf_ntf_msg_jb_cstm_mssg_haders> sf_ntf_msg_jb_cstm_mssg_haders { get; set; }
        public virtual DbSet<sf_ntf_msg_jb_xcldd_rslvd_kys_> sf_ntf_msg_jb_xcldd_rslvd_kys_ { get; set; }
        public virtual DbSet<sf_ntf_sbscrbrs_cstm_prperties> sf_ntf_sbscrbrs_cstm_prperties { get; set; }
        public virtual DbSet<sf_nws_tms_pblshd_translations> sf_nws_tms_pblshd_translations { get; set; }
        public virtual DbSet<sf_object_data> sf_object_data { get; set; }
        public virtual DbSet<sf_ocd_dpndncies> sf_ocd_dpndncies { get; set; }
        public virtual DbSet<sf_ocd_itms> sf_ocd_itms { get; set; }
        public virtual DbSet<sf_ocd_typs> sf_ocd_typs { get; set; }
        public virtual DbSet<sf_open_stat> sf_open_stat { get; set; }
        public virtual DbSet<sf_page_data> sf_page_data { get; set; }
        public virtual DbSet<sf_page_data_attrbutes> sf_page_data_attrbutes { get; set; }
        public virtual DbSet<sf_page_data_sf_language_data> sf_page_data_sf_language_data { get; set; }
        public virtual DbSet<sf_page_node> sf_page_node { get; set; }
        public virtual DbSet<sf_page_node_attrbutes> sf_page_node_attrbutes { get; set; }
        public virtual DbSet<sf_page_node_references> sf_page_node_references { get; set; }
        public virtual DbSet<sf_page_templates> sf_page_templates { get; set; }
        public virtual DbSet<sf_pblshng_mppng_sf_pp_mppng_t> sf_pblshng_mppng_sf_pp_mppng_t { get; set; }
        public virtual DbSet<sf_pblshng_mppng_src_prprty_nm> sf_pblshng_mppng_src_prprty_nm { get; set; }
        public virtual DbSet<sf_pblshng_mppng_sttngs_sf_pbl> sf_pblshng_mppng_sttngs_sf_pbl { get; set; }
        public virtual DbSet<sf_pblshng_pp_sttngs_cntnt_lnk> sf_pblshng_pp_sttngs_cntnt_lnk { get; set; }
        public virtual DbSet<sf_pblshng_pp_sttngs_ddtnl_dta> sf_pblshng_pp_sttngs_ddtnl_dta { get; set; }
        public virtual DbSet<sf_pblshng_pp_sttngs_lngge_ids> sf_pblshng_pp_sttngs_lngge_ids { get; set; }
        public virtual DbSet<sf_pckgng_addn_lnks> sf_pckgng_addn_lnks { get; set; }
        public virtual DbSet<sf_pckgng_addns> sf_pckgng_addns { get; set; }
        public virtual DbSet<sf_pckgng_addns_err_stts> sf_pckgng_addns_err_stts { get; set; }
        public virtual DbSet<sf_pckgng_addns_stts> sf_pckgng_addns_stts { get; set; }
        public virtual DbSet<sf_pckgng_pckgs> sf_pckgng_pckgs { get; set; }
        public virtual DbSet<sf_permissions> sf_permissions { get; set; }
        public virtual DbSet<sf_permissions_inheritance_map> sf_permissions_inheritance_map { get; set; }
        public virtual DbSet<sf_pg_dt_pblished_translations> sf_pg_dt_pblished_translations { get; set; }
        public virtual DbSet<sf_pg_nd_prmssnst_bjct_ttl_rs_> sf_pg_nd_prmssnst_bjct_ttl_rs_ { get; set; }
        public virtual DbSet<sf_pg_tmpltes_sf_language_data> sf_pg_tmpltes_sf_language_data { get; set; }
        public virtual DbSet<sf_pg_tmplts_pblshd_trnsltions> sf_pg_tmplts_pblshd_trnsltions { get; set; }
        public virtual DbSet<sf_pipe_mapping_translation> sf_pipe_mapping_translation { get; set; }
        public virtual DbSet<sf_presentation_data> sf_presentation_data { get; set; }
        public virtual DbSet<sf_prs_criteria_group> sf_prs_criteria_group { get; set; }
        public virtual DbSet<sf_prs_criterion> sf_prs_criterion { get; set; }
        public virtual DbSet<sf_prs_crtr_grp_sf_prs_crtrion> sf_prs_crtr_grp_sf_prs_crtrion { get; set; }
        public virtual DbSet<sf_prs_segment> sf_prs_segment { get; set; }
        public virtual DbSet<sf_prs_sgmnt_sf_prs_crtr_group> sf_prs_sgmnt_sf_prs_crtr_group { get; set; }
        public virtual DbSet<sf_publishing_mapping> sf_publishing_mapping { get; set; }
        public virtual DbSet<sf_publishing_mapping_settings> sf_publishing_mapping_settings { get; set; }
        public virtual DbSet<sf_publishing_pipe_settings> sf_publishing_pipe_settings { get; set; }
        public virtual DbSet<sf_publishing_point> sf_publishing_point { get; set; }
        public virtual DbSet<sf_publishing_point_settings> sf_publishing_point_settings { get; set; }
        public virtual DbSet<sf_publishing_throttle_settings> sf_publishing_throttle_settings { get; set; }
        public virtual DbSet<sf_rbin_item> sf_rbin_item { get; set; }
        public virtual DbSet<sf_rdsgn_media_query> sf_rdsgn_media_query { get; set; }
        public virtual DbSet<sf_rdsgn_media_query_link> sf_rdsgn_media_query_link { get; set; }
        public virtual DbSet<sf_rdsgn_media_query_rule> sf_rdsgn_media_query_rule { get; set; }
        public virtual DbSet<sf_rdsgn_nav_trnsfrmtn> sf_rdsgn_nav_trnsfrmtn { get; set; }
        public virtual DbSet<sf_roles> sf_roles { get; set; }
        public virtual DbSet<sf_scheduled_tasks> sf_scheduled_tasks { get; set; }
        public virtual DbSet<sf_schema_vrsns> sf_schema_vrsns { get; set; }
        public virtual DbSet<sf_schema_vrsns_meta_types> sf_schema_vrsns_meta_types { get; set; }
        public virtual DbSet<sf_scrty_rts_prmssnst_bjct_ttl> sf_scrty_rts_prmssnst_bjct_ttl { get; set; }
        public virtual DbSet<sf_scrty_rts_spprtd_prmssn_sts> sf_scrty_rts_spprtd_prmssn_sts { get; set; }
        public virtual DbSet<sf_security_roots> sf_security_roots { get; set; }
        public virtual DbSet<sf_site_data_src> sf_site_data_src { get; set; }
        public virtual DbSet<sf_site_data_src_lnks> sf_site_data_src_lnks { get; set; }
        public virtual DbSet<sf_site_item_links> sf_site_item_links { get; set; }
        public virtual DbSet<sf_sitefinity_profile> sf_sitefinity_profile { get; set; }
        public virtual DbSet<sf_sites> sf_sites { get; set; }
        public virtual DbSet<sf_sites_culture_keys> sf_sites_culture_keys { get; set; }
        public virtual DbSet<sf_sites_domain_aliases> sf_sites_domain_aliases { get; set; }
        public virtual DbSet<sf_sites_sf_permissions> sf_sites_sf_permissions { get; set; }
        public virtual DbSet<sf_stat_sentence> sf_stat_sentence { get; set; }
        public virtual DbSet<sf_subscriber> sf_subscriber { get; set; }
        public virtual DbSet<sf_subscription_info> sf_subscription_info { get; set; }
        public virtual DbSet<sf_sync_lock> sf_sync_lock { get; set; }
        public virtual DbSet<sf_synonyms> sf_synonyms { get; set; }
        public virtual DbSet<sf_taxa> sf_taxa { get; set; }
        public virtual DbSet<sf_taxa_attrbutes> sf_taxa_attrbutes { get; set; }
        public virtual DbSet<sf_taxonomies> sf_taxonomies { get; set; }
        public virtual DbSet<sf_taxonomy_statistic> sf_taxonomy_statistic { get; set; }
        public virtual DbSet<sf_tr_jbs> sf_tr_jbs { get; set; }
        public virtual DbSet<sf_tr_prjcts> sf_tr_prjcts { get; set; }
        public virtual DbSet<sf_tr_sources> sf_tr_sources { get; set; }
        public virtual DbSet<sf_tr_trnsltns> sf_tr_trnsltns { get; set; }
        public virtual DbSet<sf_tr_units> sf_tr_units { get; set; }
        public virtual DbSet<sf_txnms_prmssnst_bjct_ttl_rs_> sf_txnms_prmssnst_bjct_ttl_rs_ { get; set; }
        public virtual DbSet<sf_txnms_spprtd_prmission_sets> sf_txnms_spprtd_prmission_sets { get; set; }
        public virtual DbSet<sf_unsubscription_info> sf_unsubscription_info { get; set; }
        public virtual DbSet<sf_url_data> sf_url_data { get; set; }
        public virtual DbSet<sf_user_action> sf_user_action { get; set; }
        public virtual DbSet<sf_user_link> sf_user_link { get; set; }
        public virtual DbSet<sf_user_profile> sf_user_profile { get; set; }
        public virtual DbSet<sf_user_profile_link> sf_user_profile_link { get; set; }
        public virtual DbSet<sf_users> sf_users { get; set; }
        public virtual DbSet<sf_version_chnges> sf_version_chnges { get; set; }
        public virtual DbSet<sf_version_dependency> sf_version_dependency { get; set; }
        public virtual DbSet<sf_version_serial_info> sf_version_serial_info { get; set; }
        public virtual DbSet<sf_version_trunks> sf_version_trunks { get; set; }
        public virtual DbSet<sf_vesion_items> sf_vesion_items { get; set; }
        public virtual DbSet<sf_vnts_published_translations> sf_vnts_published_translations { get; set; }
        public virtual DbSet<sf_wfl_definition> sf_wfl_definition { get; set; }
        public virtual DbSet<sf_wfl_dfntn_prmssnst_bjct_ttl> sf_wfl_dfntn_prmssnst_bjct_ttl { get; set; }
        public virtual DbSet<sf_wfl_dfntn_spprtd_prmssn_sts> sf_wfl_dfntn_spprtd_prmssn_sts { get; set; }
        public virtual DbSet<sf_wfl_level> sf_wfl_level { get; set; }
        public virtual DbSet<sf_wfl_lvl_cstm_mil_recipients> sf_wfl_lvl_cstm_mil_recipients { get; set; }
        public virtual DbSet<sf_wfl_permission> sf_wfl_permission { get; set; }
        public virtual DbSet<sf_wfl_scope> sf_wfl_scope { get; set; }
        public virtual DbSet<sf_wfl_type_scope> sf_wfl_type_scope { get; set; }
        public virtual DbSet<sf_xml_config_items> sf_xml_config_items { get; set; }
        public virtual DbSet<Skill> Skill { get; set; }
        public virtual DbSet<SyncSchedulerExecution> SyncSchedulerExecution { get; set; }
        public virtual DbSet<SyncTask> SyncTask { get; set; }
        public virtual DbSet<SyncTaskExecution> SyncTaskExecution { get; set; }
        public virtual DbSet<SyncTaskLock> SyncTaskLock { get; set; }
        public virtual DbSet<tbl_perfilador_C_Preguntas> tbl_perfilador_C_Preguntas { get; set; }
        public virtual DbSet<tbl_perfilador_Destinos> tbl_perfilador_Destinos { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<voa_keygen> voa_keygen { get; set; }
        public virtual DbSet<MSreplication_options> MSreplication_options { get; set; }
        public virtual DbSet<paso_portal_C_Aseguradora> paso_portal_C_Aseguradora { get; set; }
        public virtual DbSet<paso_portal_C_Auto> paso_portal_C_Auto { get; set; }
        public virtual DbSet<paso_portal_C_Coberturas> paso_portal_C_Coberturas { get; set; }
        public virtual DbSet<paso_portal_C_DescEstados> paso_portal_C_DescEstados { get; set; }
        public virtual DbSet<paso_portal_C_Estados> paso_portal_C_Estados { get; set; }
        public virtual DbSet<paso_portal_C_Modelos> paso_portal_C_Modelos { get; set; }
        public virtual DbSet<paso_portal_C_PlazoAseguradora> paso_portal_C_PlazoAseguradora { get; set; }
        public virtual DbSet<paso_portal_C_Plazos> paso_portal_C_Plazos { get; set; }
        public virtual DbSet<paso_portal_C_Tipo> paso_portal_C_Tipo { get; set; }
        public virtual DbSet<spt_fallback_db> spt_fallback_db { get; set; }
        public virtual DbSet<spt_fallback_dev> spt_fallback_dev { get; set; }
        public virtual DbSet<spt_fallback_usg> spt_fallback_usg { get; set; }
        public virtual DbSet<spt_monitor> spt_monitor { get; set; }
        public virtual DbSet<tbl_cotizador_estados> tbl_cotizador_estados { get; set; }
        public virtual DbSet<tbl_cotizador_paises> tbl_cotizador_paises { get; set; }
        public virtual DbSet<tbl_perfilador_Respuestas> tbl_perfilador_Respuestas { get; set; }
        public virtual DbSet<tbl_portal_C_Aseguradora> tbl_portal_C_Aseguradora { get; set; }
        public virtual DbSet<tbl_portal_C_Auto> tbl_portal_C_Auto { get; set; }
        public virtual DbSet<tbl_portal_C_Coberturas> tbl_portal_C_Coberturas { get; set; }
        public virtual DbSet<tbl_portal_C_CoeficienteAnualidad> tbl_portal_C_CoeficienteAnualidad { get; set; }
        public virtual DbSet<tbl_portal_C_DescEstados> tbl_portal_C_DescEstados { get; set; }
        public virtual DbSet<tbl_portal_C_DescEstados_V> tbl_portal_C_DescEstados_V { get; set; }
        public virtual DbSet<tbl_portal_C_Estados> tbl_portal_C_Estados { get; set; }
        public virtual DbSet<tbl_portal_C_Modelos> tbl_portal_C_Modelos { get; set; }
        public virtual DbSet<tbl_portal_C_plan> tbl_portal_C_plan { get; set; }
        public virtual DbSet<tbl_portal_C_PlazoAseguradora> tbl_portal_C_PlazoAseguradora { get; set; }
        public virtual DbSet<tbl_portal_C_Plazos> tbl_portal_C_Plazos { get; set; }
        public virtual DbSet<tbl_portal_C_Tipo> tbl_portal_C_Tipo { get; set; }
        public virtual DbSet<tbl_portal_C_tipo_persona> tbl_portal_C_tipo_persona { get; set; }
        public virtual DbSet<tbl_portal_C_TipoUso> tbl_portal_C_TipoUso { get; set; }
        public virtual DbSet<tbl_portal_Distribuidores> tbl_portal_Distribuidores { get; set; }
        public virtual DbSet<tbl_portal_Llaves> tbl_portal_Llaves { get; set; }
        public virtual DbSet<tbl_portal_parametros> tbl_portal_parametros { get; set; }
        public virtual DbSet<AssignmentData> AssignmentData { get; set; }
        public virtual DbSet<ProjectData> ProjectData { get; set; }
        public virtual DbSet<spt_values> spt_values { get; set; }
    
        public virtual ObjectResult<USP_SEL_CAT_CARS_Result> USP_SEL_CAT_CARS(string cARPETA_RAIZ, string sUBCARPETA)
        {
            var cARPETA_RAIZParameter = cARPETA_RAIZ != null ?
                new ObjectParameter("CARPETA_RAIZ", cARPETA_RAIZ) :
                new ObjectParameter("CARPETA_RAIZ", typeof(string));
    
            var sUBCARPETAParameter = sUBCARPETA != null ?
                new ObjectParameter("SUBCARPETA", sUBCARPETA) :
                new ObjectParameter("SUBCARPETA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_CAT_CARS_Result>("USP_SEL_CAT_CARS", cARPETA_RAIZParameter, sUBCARPETAParameter);
        }
    
        public virtual ObjectResult<USP_SELECT_CAT_AUTOS_Result> USP_SELECT_CAT_AUTOS(string cARPETA_RAIZ, string sUBCARPETA)
        {
            var cARPETA_RAIZParameter = cARPETA_RAIZ != null ?
                new ObjectParameter("CARPETA_RAIZ", cARPETA_RAIZ) :
                new ObjectParameter("CARPETA_RAIZ", typeof(string));
    
            var sUBCARPETAParameter = sUBCARPETA != null ?
                new ObjectParameter("SUBCARPETA", sUBCARPETA) :
                new ObjectParameter("SUBCARPETA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SELECT_CAT_AUTOS_Result>("USP_SELECT_CAT_AUTOS", cARPETA_RAIZParameter, sUBCARPETAParameter);
        }
    }
}
