//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OAConflicts
    {
        public int Id { get; set; }
        public string BaseName { get; set; }
        public System.DateTimeOffset Occured { get; set; }
        public string SourceId { get; set; }
        public string DestinationId { get; set; }
        public string BaseId { get; set; }
        public string CorrelationId { get; set; }
        public string ConfigurationName { get; set; }
    
        public virtual OAImportConfigurations OAImportConfigurations { get; set; }
    }
}
