//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OAImportConfigurations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OAImportConfigurations()
        {
            this.OAConflicts = new HashSet<OAConflicts>();
            this.OASyncImportSummary = new HashSet<OASyncImportSummary>();
        }
    
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string BaseTypeName { get; set; }
        public string BaseConnectionString { get; set; }
        public byte BaseIsUpdateRequired { get; set; }
        public string SourceTypeName { get; set; }
        public string SourceConnectionString { get; set; }
        public byte SourceIsForwardMapped { get; set; }
        public byte SourceIsUpdateRequired { get; set; }
        public string DestinationTypeName { get; set; }
        public string DestinationConectionString { get; set; }
        public byte DestinationIsForwardMapped { get; set; }
        public byte DestinationIsUpdateRequired { get; set; }
        public string BaseConfig { get; set; }
        public string SourceConfig { get; set; }
        public string DestinationConfig { get; set; }
        public string SerializedMapping { get; set; }
        public int ImportType { get; set; }
        public int LogLevel { get; set; }
        public int PageSize { get; set; }
        public int TransactionSize { get; set; }
        public byte IntermediateCommits { get; set; }
        public byte CopyToBase { get; set; }
        public Nullable<byte> MarkedForDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OAConflicts> OAConflicts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OASyncImportSummary> OASyncImportSummary { get; set; }
    }
}
