//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OASyncLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OASyncLog()
        {
            this.OASyncImportSummary = new HashSet<OASyncImportSummary>();
        }
    
        public int Id { get; set; }
        public System.DateTimeOffset Executed { get; set; }
        public int Action { get; set; }
        public string SourceId { get; set; }
        public string DestinationId { get; set; }
        public string BaseId { get; set; }
        public string CorrelationId { get; set; }
        public string BaseName { get; set; }
        public string Description { get; set; }
        public Nullable<int> ListSummary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OASyncImportSummary> OASyncImportSummary { get; set; }
    }
}
