//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OASyncImportSummary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OASyncImportSummary()
        {
            this.OASyncLog = new HashSet<OASyncLog>();
        }
    
        public int Id { get; set; }
        public int ImportStatus { get; set; }
        public System.DateTimeOffset ImportStart { get; set; }
        public Nullable<System.DateTimeOffset> ImportEnd { get; set; }
        public string ConfigurationName { get; set; }
        public Nullable<int> LastErrorSynchronizationLog { get; set; }
    
        public virtual OAImportConfigurations OAImportConfigurations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OASyncLog> OASyncLog { get; set; }
    }
}
