//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoVersion
    {
        public int PoId { get; set; }
        public int Version { get; set; }
        public string PoNumber { get; set; }
        public System.DateTime ReceptionDate { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string CurrencyId { get; set; }
        public string Comments { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Po Po { get; set; }
    }
}
