//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectData
    {
        public int ResourceId { get; set; }
        public string ResourceFirstName { get; set; }
        public string ResourceLastName { get; set; }
        public int AssignmentId { get; set; }
        public string BillingCountryId { get; set; }
        public string Sponsor { get; set; }
        public string AssignmentComments { get; set; }
        public short Year { get; set; }
        public byte Month { get; set; }
        public Nullable<decimal> FteClient { get; set; }
        public Nullable<decimal> FteReal { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> AssignmentPeriodDateFrom { get; set; }
        public Nullable<System.DateTime> AssignmentPeriodDateTo { get; set; }
        public string AssignmentPeriodComments { get; set; }
        public int ProjectId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public byte ProjectTypeId { get; set; }
        public byte ProjectStateId { get; set; }
        public string ProjectName { get; set; }
        public string Summary { get; set; }
        public Nullable<System.DateTime> ProjectBeginDate { get; set; }
        public Nullable<System.DateTime> ProjectEndDate { get; set; }
        public string CurrencyId { get; set; }
        public bool NonQuotable { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Currency { get; set; }
        public string ClientName { get; set; }
        public string BillingCountry { get; set; }
        public string ProjectState { get; set; }
        public string ProjectType { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<int> PoId { get; set; }
        public string PoNumber { get; set; }
    }
}
