//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_ab_test
    {
        public Nullable<System.Guid> winner_variation_id { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> stop_date { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.Guid> site_id { get; set; }
        public Nullable<System.Guid> selected_variation_id { get; set; }
        public Nullable<System.Guid> tested_item_id { get; set; }
        public Nullable<System.Guid> owner { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public System.Guid id { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string culture { get; set; }
        public string api_key { get; set; }
    }
}
