//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_ab_campaign
    {
        public Nullable<int> winning_condition { get; set; }
        public Nullable<System.Guid> winner_issue_original_id { get; set; }
        public Nullable<System.Guid> winner_issue_id { get; set; }
        public Nullable<int> testing_sample_percentage { get; set; }
        public string testing_note { get; set; }
        public Nullable<System.DateTime> testing_ends { get; set; }
        public Nullable<System.Guid> root_campaign_id { get; set; }
        public string nme { get; set; }
        public System.DateTime last_modified { get; set; }
        public System.Guid id { get; set; }
        public Nullable<System.DateTime> date_sent { get; set; }
        public string conclusion { get; set; }
        public Nullable<System.Guid> campaign_b_id { get; set; }
        public Nullable<System.Guid> campaign_a_id { get; set; }
        public string application_name { get; set; }
        public Nullable<int> a_b_testing_status { get; set; }
        public short voa_version { get; set; }
    }
}
