//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_ab_test_goal
    {
        public string predicate_operator { get; set; }
        public int ordinal { get; set; }
        public string object_name { get; set; }
        public string object_id { get; set; }
        public string object_culture { get; set; }
        public byte is_primary { get; set; }
        public System.Guid id { get; set; }
        public int goal_type { get; set; }
        public string goal_nme_rsrc_key { get; set; }
        public Nullable<System.Guid> ab_test_id { get; set; }
    }
}
