//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_ab_test_variation
    {
        public int traffic_distribution { get; set; }
        public Nullable<System.Guid> data_item_id { get; set; }
        public int ordinal { get; set; }
        public string name { get; set; }
        public byte is_original { get; set; }
        public System.Guid id { get; set; }
        public Nullable<System.Guid> ab_test_id { get; set; }
    }
}
