//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_approval_tracking_record
    {
        public Nullable<System.Guid> workflow_item_id { get; set; }
        public Nullable<System.Guid> user_id { get; set; }
        public string status { get; set; }
        public string note { get; set; }
        public System.DateTime last_modified { get; set; }
        public System.Guid id { get; set; }
        public System.DateTime date_created { get; set; }
        public int culture { get; set; }
        public string application_name { get; set; }
        public short voa_version { get; set; }
    }
}
