//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_addresses
    {
        public string zip { get; set; }
        public string street { get; set; }
        public string state_code { get; set; }
        public Nullable<int> map_zoom_level { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> latitude { get; set; }
        public System.Guid id { get; set; }
        public string country_code { get; set; }
        public string city { get; set; }
    }
}
