//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_bounce_stat
    {
        public Nullable<System.Guid> sf_subscriber_id { get; set; }
        public string smtp_status { get; set; }
        public int retry_count { get; set; }
        public Nullable<int> message_status { get; set; }
        public System.DateTime last_modified { get; set; }
        public byte is_processing { get; set; }
        public System.Guid id { get; set; }
        public Nullable<System.Guid> sf_campaign_id { get; set; }
        public int bounce_status { get; set; }
        public string application_name { get; set; }
        public string additional_info { get; set; }
        public short voa_version { get; set; }
    }
}
