//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_cs_threads
    {
        public string type { get; set; }
        public string title { get; set; }
        public string resolve_key { get; set; }
        public byte require_authentication { get; set; }
        public byte require_approval { get; set; }
        public System.Guid parent_group_id { get; set; }
        public System.DateTime last_modified { get; set; }
        public string language { get; set; }
        public byte is_closed { get; set; }
        public System.Guid id { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string data_source { get; set; }
        public int comments_count { get; set; }
        public string behavior { get; set; }
        public Nullable<decimal> average_rating { get; set; }
        public string author_name { get; set; }
        public Nullable<System.Guid> author_id { get; set; }
        public string author_email { get; set; }
    }
}
