//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_control_properties
    {
        public string val { get; set; }
        public string validation { get; set; }
        public Nullable<System.Guid> prnt_prop_id { get; set; }
        public float ordinal { get; set; }
        public string nme { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public string language { get; set; }
        public System.Guid id { get; set; }
        public int flags { get; set; }
        public string description_ { get; set; }
        public Nullable<System.Guid> control_id { get; set; }
        public string caption_ { get; set; }
        public string app_name { get; set; }
        public short voa_version { get; set; }
    }
}
