//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_cs_comments
    {
        public string status { get; set; }
        public string resolve_key { get; set; }
        public Nullable<decimal> rating { get; set; }
        public System.Guid parent_thread_id { get; set; }
        public string message { get; set; }
        public string last_modified_by_name { get; set; }
        public string last_modified_by_email { get; set; }
        public Nullable<System.Guid> last_modified_by { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string custom_data { get; set; }
        public string author_name { get; set; }
        public string author_ip_address { get; set; }
        public Nullable<System.Guid> author_id { get; set; }
        public string author_email { get; set; }
    }
}
