//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_cnt_locations
    {
        public Nullable<System.Guid> site_id { get; set; }
        public Nullable<System.Guid> redirect_page_id { get; set; }
        public int priority { get; set; }
        public Nullable<System.Guid> page_id { get; set; }
        public string lang { get; set; }
        public string item_type { get; set; }
        public string item_provider { get; set; }
        public string item_descendant_type { get; set; }
        public System.Guid id { get; set; }
        public Nullable<System.Guid> control_id { get; set; }
        public string app_name { get; set; }
    }
}
