//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_campaign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_campaign()
        {
            this.sf_campaign_sf_campaign_link = new HashSet<sf_campaign_sf_campaign_link>();
        }
    
        public Nullable<byte> use_google_tracking { get; set; }
        public string short_id { get; set; }
        public Nullable<System.Guid> rootCampaign_id { get; set; }
        public string reply_to_email { get; set; }
        public Nullable<System.Guid> related_notification_job { get; set; }
        public string nme { get; set; }
        public string message_subject { get; set; }
        public Nullable<System.Guid> id3 { get; set; }
        public Nullable<System.Guid> id2 { get; set; }
        public System.DateTime last_modified { get; set; }
        public byte is_ready_for_sending { get; set; }
        public System.Guid id { get; set; }
        public string from_name { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public int campaign_state { get; set; }
        public string application_name { get; set; }
        public short voa_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_campaign_sf_campaign_link> sf_campaign_sf_campaign_link { get; set; }
    }
}
