//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_content_relation
    {
        public string subject_type { get; set; }
        public string subject_provider { get; set; }
        public Nullable<System.Guid> subject_id { get; set; }
        public string relation_type { get; set; }
        public string object_type { get; set; }
        public string object_provider { get; set; }
        public Nullable<System.Guid> object_id { get; set; }
        public System.Guid key { get; set; }
    }
}
