//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_content_link
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_content_link()
        {
            this.sf_content_link_attrbutes = new HashSet<sf_content_link_attrbutes>();
        }
    
        public string parent_item_type { get; set; }
        public string parent_item_provider_name { get; set; }
        public Nullable<System.Guid> parent_item_id { get; set; }
        public string parent_item_additional_info { get; set; }
        public float ordinal { get; set; }
        public System.DateTime last_modified { get; set; }
        public byte is_parent_deleted { get; set; }
        public byte is_child_deleted { get; set; }
        public System.Guid id { get; set; }
        public string component_property_name { get; set; }
        public string child_item_type { get; set; }
        public string child_item_provider_name { get; set; }
        public Nullable<System.Guid> child_item_id { get; set; }
        public string child_item_additional_info { get; set; }
        public byte available_for_temp { get; set; }
        public byte available_for_master { get; set; }
        public byte available_for_live { get; set; }
        public string app_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_content_link_attrbutes> sf_content_link_attrbutes { get; set; }
    }
}
