//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_calendars
    {
        public string url_name_ { get; set; }
        public string title_ { get; set; }
        public System.DateTime publication_date { get; set; }
        public Nullable<System.Guid> ownr { get; set; }
        public System.DateTime last_modified { get; set; }
        public System.Guid id { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public string description_ { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string color { get; set; }
        public string app_name { get; set; }
    }
}
