//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_campaign_link
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_campaign_link()
        {
            this.sf_campaign_sf_campaign_link = new HashSet<sf_campaign_sf_campaign_link>();
        }
    
        public string url { get; set; }
        public System.DateTime last_modified { get; set; }
        public System.Guid id { get; set; }
        public Nullable<System.Guid> id2 { get; set; }
        public string application_name { get; set; }
        public short voa_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_campaign_sf_campaign_link> sf_campaign_sf_campaign_link { get; set; }
    }
}
