//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_chunks
    {
        public int sze { get; set; }
        public int ordinal { get; set; }
        public System.Guid file_id { get; set; }
        public byte[] dta { get; set; }
        public short voa_version { get; set; }
    }
}
