//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_dynamic_content
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_dynamic_content()
        {
            this.sf_dynmc_cntnt_pblshd_trnsltns = new HashSet<sf_dynmc_cntnt_pblshd_trnsltns>();
            this.sf_dynmc_cntnt_sf_lnguage_data = new HashSet<sf_dynmc_cntnt_sf_lnguage_data>();
            this.sf_permissions = new HashSet<sf_permissions>();
        }
    
        public Nullable<byte> was_published { get; set; }
        public byte visible { get; set; }
        public int vrsion { get; set; }
        public string url_name_ { get; set; }
        public string system_parent_type { get; set; }
        public Nullable<System.Guid> system_parent_id { get; set; }
        public int status { get; set; }
        public System.DateTime publication_date { get; set; }
        public Nullable<System.Guid> ownr { get; set; }
        public Nullable<System.Guid> original_content_id { get; set; }
        public Nullable<System.Guid> last_modified_by { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public string item_default_url_ { get; set; }
        public byte inherits_permissions { get; set; }
        public Nullable<byte> include_in_sitemap { get; set; }
        public System.Guid base_id { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public byte can_inherit_permissions { get; set; }
        public string approval_workflow_state_ { get; set; }
        public string application_name { get; set; }
        public short voa_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_dynmc_cntnt_pblshd_trnsltns> sf_dynmc_cntnt_pblshd_trnsltns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_dynmc_cntnt_sf_lnguage_data> sf_dynmc_cntnt_sf_lnguage_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_permissions> sf_permissions { get; set; }
    }
}
