//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_dashboard_watchlist
    {
        public Nullable<System.Guid> user_id { get; set; }
        public System.Guid id { get; set; }
        public Nullable<System.Guid> dashboard_log_entry_id { get; set; }
    }
}
