//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_dynamic_list
    {
        public int sf_dynamic_list_id { get; set; }
        public string list_key { get; set; }
        public string last_name_mapped_field { get; set; }
        public string first_name_mapped_field { get; set; }
        public string email_mapped_field { get; set; }
        public string dynamic_list_provider_name { get; set; }
        public string connection_name { get; set; }
        public short voa_version { get; set; }
        public Nullable<System.Guid> dynamic_list_id { get; set; }
    }
}
