//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_draft_pages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_draft_pages()
        {
            this.sf_drft_pages_sf_language_data = new HashSet<sf_drft_pages_sf_language_data>();
        }
    
        public int vrsion { get; set; }
        public Nullable<System.Guid> ownr { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public byte is_temp_draft { get; set; }
        public System.Guid id { get; set; }
        public string approval_workflow_state_ { get; set; }
        public string app_name { get; set; }
        public int voa_class { get; set; }
        public short voa_version { get; set; }
        public string theme { get; set; }
        public Nullable<int> url_evaluation_mode { get; set; }
        public string template_name { get; set; }
        public Nullable<System.Guid> template_id { get; set; }
        public string renderer { get; set; }
        public Nullable<System.Guid> personalization_segment_id { get; set; }
        public Nullable<System.Guid> personalization_master_id { get; set; }
        public Nullable<System.Guid> page_id { get; set; }
        public string master_page { get; set; }
        public Nullable<int> last_control_id2 { get; set; }
        public Nullable<byte> is_personalized { get; set; }
        public Nullable<byte> include_script_manger { get; set; }
        public Nullable<int> flags { get; set; }
        public string external_page { get; set; }
        public string theme2 { get; set; }
        public Nullable<System.Guid> personalization_segment_id2 { get; set; }
        public Nullable<System.Guid> personalization_master_id2 { get; set; }
        public string master_page2 { get; set; }
        public Nullable<int> last_control_id { get; set; }
        public string ky { get; set; }
        public Nullable<byte> is_personalized2 { get; set; }
        public Nullable<byte> include_script_manger2 { get; set; }
        public Nullable<int> submit_restriction { get; set; }
        public Nullable<int> submit_action { get; set; }
        public Nullable<int> submit_action_after_update { get; set; }
        public Nullable<int> form_label_placement { get; set; }
        public string rules { get; set; }
        public string nme { get; set; }
        public string redirect_page_url { get; set; }
        public string redirect_page_url_after_update { get; set; }
        public string css_class { get; set; }
        public Nullable<int> last_control_id3 { get; set; }
        public Nullable<byte> is_temp_form { get; set; }
        public Nullable<bool> send_confirmation_email { get; set; }
        public string success_message_ { get; set; }
        public string sccss_mssge_after_form_update_ { get; set; }
        public Nullable<System.Guid> content_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_drft_pages_sf_language_data> sf_drft_pages_sf_language_data { get; set; }
    }
}
