//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_dashboard_log
    {
        public Nullable<System.Guid> user_id { get; set; }
        public string item_title { get; set; }
        public System.DateTime timestamp { get; set; }
        public string status { get; set; }
        public Nullable<System.Guid> site_id { get; set; }
        public string language { get; set; }
        public string item_type { get; set; }
        public string item_provider { get; set; }
        public string item_id { get; set; }
        public System.Guid id { get; set; }
    }
}
