//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_ec_customer_profile
    {
        public System.Guid id { get; set; }
        public string shipping_state_region { get; set; }
        public string shipping_postal_code { get; set; }
        public string shipping_phone_number { get; set; }
        public string shipping_last_name { get; set; }
        public string shipping_first_name { get; set; }
        public string shipping_email { get; set; }
        public string shipping_country { get; set; }
        public string shipping_company { get; set; }
        public string shipping_city { get; set; }
        public string shipping_address2 { get; set; }
        public string shipping_address1 { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string billing_state_region { get; set; }
        public string billing_postal_code { get; set; }
        public string billing_phone_number { get; set; }
        public string billing_email { get; set; }
        public string billing_country { get; set; }
        public string billing_company { get; set; }
        public string billing_city { get; set; }
        public string billing_address2 { get; set; }
        public string billing_address1 { get; set; }
    
        public virtual sf_user_profile sf_user_profile { get; set; }
    }
}
