//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_files_monitor_data
    {
        public string package_name { get; set; }
        public System.Guid id { get; set; }
        public string file_path { get; set; }
        public string file_name { get; set; }
    }
}
