//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_frm_dscrptn_sf_lnguage_data
    {
        public System.Guid content_id { get; set; }
        public int seq { get; set; }
        public Nullable<System.Guid> id { get; set; }
    
        public virtual sf_form_description sf_form_description { get; set; }
        public virtual sf_language_data sf_language_data { get; set; }
    }
}
