//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_form_description
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_form_description()
        {
            this.sf_form_description_category = new HashSet<sf_form_description_category>();
            this.sf_frm_dscrptn_pblshd_trnsltns = new HashSet<sf_frm_dscrptn_pblshd_trnsltns>();
            this.sf_frm_dscrptn_sf_lnguage_data = new HashSet<sf_frm_dscrptn_sf_lnguage_data>();
            this.sf_form_description_sf_commnt = new HashSet<sf_form_description_sf_commnt>();
            this.sf_frm_dscrptn_sf_prsnttn_data = new HashSet<sf_frm_dscrptn_sf_prsnttn_data>();
            this.sf_form_description_tags = new HashSet<sf_form_description_tags>();
            this.sf_form_description_attrbutes = new HashSet<sf_form_description_attrbutes>();
            this.sf_permissions = new HashSet<sf_permissions>();
        }
    
        public int status { get; set; }
        public int post_rights { get; set; }
        public System.Guid content_id { get; set; }
        public byte visible { get; set; }
        public Nullable<System.Guid> ownr { get; set; }
        public string app_name { get; set; }
        public int views_count { get; set; }
        public decimal votes_sum { get; set; }
        public long votes_count { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public System.DateTime publication_date { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public int vrsion { get; set; }
        public Nullable<System.Guid> default_page_id { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public Nullable<byte> allow_track_backs { get; set; }
        public Nullable<byte> allow_comments { get; set; }
        public Nullable<byte> approve_comments { get; set; }
        public Nullable<byte> email_author { get; set; }
        public string content_state { get; set; }
        public string draft_culture { get; set; }
        public Nullable<System.Guid> original_content_id { get; set; }
        public Nullable<System.Guid> last_modified_by { get; set; }
        public string source_key { get; set; }
        public Nullable<byte> include_in_sitemap { get; set; }
        public string title_ { get; set; }
        public string description_ { get; set; }
        public string url_name_ { get; set; }
        public int submit_restriction { get; set; }
        public int submit_action { get; set; }
        public int submit_action_after_update { get; set; }
        public int form_label_placement { get; set; }
        public string nme { get; set; }
        public string rules { get; set; }
        public string redirect_page_url { get; set; }
        public string redirect_page_url_after_update { get; set; }
        public string css_class { get; set; }
        public Nullable<System.Guid> locked_by { get; set; }
        public long form_entries_seed { get; set; }
        public int last_control_id { get; set; }
        public byte inherits_permissions { get; set; }
        public byte can_inherit_permissions { get; set; }
        public Nullable<System.Guid> subscr_lst_id { get; set; }
        public Nullable<System.Guid> subscr_lst_id_after_update { get; set; }
        public Nullable<System.Guid> library_id { get; set; }
        public int frmwrk { get; set; }
        public Nullable<bool> send_confirmation_email { get; set; }
        public string success_message_ { get; set; }
        public string sccss_mssge_after_form_update_ { get; set; }
        public short voa_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_form_description_category> sf_form_description_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_frm_dscrptn_pblshd_trnsltns> sf_frm_dscrptn_pblshd_trnsltns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_frm_dscrptn_sf_lnguage_data> sf_frm_dscrptn_sf_lnguage_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_form_description_sf_commnt> sf_form_description_sf_commnt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_frm_dscrptn_sf_prsnttn_data> sf_frm_dscrptn_sf_prsnttn_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_form_description_tags> sf_form_description_tags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_form_description_attrbutes> sf_form_description_attrbutes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_permissions> sf_permissions { get; set; }
    }
}
