//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_failed_deliveries
    {
        public string subscriber_resolve_key { get; set; }
        public Nullable<System.Guid> subscriber_id { get; set; }
        public Nullable<System.Guid> job_id { get; set; }
        public System.Guid id { get; set; }
        public string failure_reason { get; set; }
        public System.DateTime fail_time { get; set; }
        public string description { get; set; }
        public string delivery_address { get; set; }
    }
}
