//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_forums
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_forums()
        {
            this.sf_permissions = new HashSet<sf_permissions>();
        }
    
        public string url_name_ { get; set; }
        public string title { get; set; }
        public int threads_count { get; set; }
        public Nullable<System.Guid> subscr_lst_id { get; set; }
        public int posts_count { get; set; }
        public Nullable<System.Guid> ownr { get; set; }
        public float ordinal { get; set; }
        public Nullable<System.Guid> last_thread_id { get; set; }
        public string last_post_user_name { get; set; }
        public Nullable<System.Guid> last_post_user_id { get; set; }
        public Nullable<System.Guid> last_post_id { get; set; }
        public Nullable<System.DateTime> last_post_date { get; set; }
        public System.DateTime last_modified { get; set; }
        public string item_default_url_ { get; set; }
        public byte is_locked { get; set; }
        public byte inherits_permissions { get; set; }
        public Nullable<byte> include_in_sitemap { get; set; }
        public System.Guid id { get; set; }
        public Nullable<System.Guid> icon_id { get; set; }
        public Nullable<System.Guid> group_id { get; set; }
        public string description { get; set; }
        public Nullable<System.Guid> defaultPageId { get; set; }
        public System.DateTime date_created { get; set; }
        public byte can_inherit_permissions { get; set; }
        public string attachmentsRequiredRole { get; set; }
        public string app_name { get; set; }
        public string allowed_attachment_extensions { get; set; }
        public byte allowAttachments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_permissions> sf_permissions { get; set; }
    }
}
