//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_folders
    {
        public string url_name_ { get; set; }
        public string title_ { get; set; }
        public Nullable<System.Guid> root_id { get; set; }
        public string path { get; set; }
        public Nullable<System.Guid> parent_id { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public byte is_deleted { get; set; }
        public System.Guid id { get; set; }
        public string description_ { get; set; }
        public Nullable<System.Guid> cover_id { get; set; }
        public string app_name { get; set; }
        public short voa_version { get; set; }
    }
}
