//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_forum_groups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_forum_groups()
        {
            this.sf_permissions = new HashSet<sf_permissions>();
        }
    
        public string url_name_ { get; set; }
        public string title { get; set; }
        public float ordinal { get; set; }
        public System.DateTime last_modified { get; set; }
        public string item_default_url_ { get; set; }
        public byte is_locked { get; set; }
        public byte is_default { get; set; }
        public byte inherits_permissions { get; set; }
        public System.Guid id { get; set; }
        public string description { get; set; }
        public byte can_inherit_permissions { get; set; }
        public string app_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_permissions> sf_permissions { get; set; }
    }
}
