//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_issue_subscriber_report
    {
        public Nullable<System.Guid> sf_subscriber_id { get; set; }
        public int message_status { get; set; }
        public System.DateTime last_modified { get; set; }
        public Nullable<System.Guid> sf_campaign_id { get; set; }
        public System.Guid id { get; set; }
        public byte has_unsubscribed { get; set; }
        public byte has_clicked { get; set; }
        public int delivery_status { get; set; }
        public Nullable<System.DateTime> date_opened { get; set; }
        public string application_name { get; set; }
        public short voa_version { get; set; }
    }
}
