//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_idsrv_tokens
    {
        public int token_type { get; set; }
        public string token_key { get; set; }
        public System.DateTime last_modified { get; set; }
        public Nullable<System.Guid> idsrv_key { get; set; }
        public System.Guid id { get; set; }
        public System.DateTime expire_date { get; set; }
        public string data { get; set; }
        public string app_name { get; set; }
    }
}
