//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_lic_user_activity
    {
        public System.Guid user_id { get; set; }
        public string token_id { get; set; }
        public string provider_name { get; set; }
        public string login_ip { get; set; }
        public Nullable<System.DateTime> last_login_date { get; set; }
        public System.DateTime last_activity_date { get; set; }
        public byte is_logged_in { get; set; }
        public byte is_backend_user { get; set; }
    }
}
