//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_language_data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_language_data()
        {
            this.sf_blog_posts_sf_language_data = new HashSet<sf_blog_posts_sf_language_data>();
            this.sf_cntnt_tems_sf_language_data = new HashSet<sf_cntnt_tems_sf_language_data>();
            this.sf_drft_pages_sf_language_data = new HashSet<sf_drft_pages_sf_language_data>();
            this.sf_dynmc_cntnt_sf_lnguage_data = new HashSet<sf_dynmc_cntnt_sf_lnguage_data>();
            this.sf_events_sf_language_data = new HashSet<sf_events_sf_language_data>();
            this.sf_frm_dscrptn_sf_lnguage_data = new HashSet<sf_frm_dscrptn_sf_lnguage_data>();
            this.sf_list_items_sf_language_data = new HashSet<sf_list_items_sf_language_data>();
            this.sf_md_content_sf_language_data = new HashSet<sf_md_content_sf_language_data>();
            this.sf_news_items_sf_language_data = new HashSet<sf_news_items_sf_language_data>();
            this.sf_page_data_sf_language_data = new HashSet<sf_page_data_sf_language_data>();
            this.sf_pg_tmpltes_sf_language_data = new HashSet<sf_pg_tmpltes_sf_language_data>();
        }
    
        public Nullable<System.DateTime> scheduled_date { get; set; }
        public System.DateTime publication_date { get; set; }
        public System.DateTime last_modified { get; set; }
        public int language_version { get; set; }
        public string language { get; set; }
        public System.Guid id { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public int content_state { get; set; }
        public string app_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_blog_posts_sf_language_data> sf_blog_posts_sf_language_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_cntnt_tems_sf_language_data> sf_cntnt_tems_sf_language_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_drft_pages_sf_language_data> sf_drft_pages_sf_language_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_dynmc_cntnt_sf_lnguage_data> sf_dynmc_cntnt_sf_lnguage_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_events_sf_language_data> sf_events_sf_language_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_frm_dscrptn_sf_lnguage_data> sf_frm_dscrptn_sf_lnguage_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_list_items_sf_language_data> sf_list_items_sf_language_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_md_content_sf_language_data> sf_md_content_sf_language_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_news_items_sf_language_data> sf_news_items_sf_language_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_page_data_sf_language_data> sf_page_data_sf_language_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_pg_tmpltes_sf_language_data> sf_pg_tmpltes_sf_language_data { get; set; }
    }
}
