//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_link_click_stat
    {
        public int sf_link_click_stat_id { get; set; }
        public string url { get; set; }
        public Nullable<System.Guid> subscriber_id { get; set; }
        public System.DateTime date_time_clicked { get; set; }
        public Nullable<System.Guid> campaign_id { get; set; }
        public short voa_version { get; set; }
    }
}
