//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_lst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_lst()
        {
            this.sf_subscriber = new HashSet<sf_subscriber>();
        }
    
        public Nullable<System.Guid> wlcme_template_id { get; set; }
        public string welcome_message_subject { get; set; }
        public string welcome_message_email_address { get; set; }
        public Nullable<System.Guid> unsubscribe_page_id { get; set; }
        public int total_unsubscriptions { get; set; }
        public string title_ { get; set; }
        public string subscription_reminder_ { get; set; }
        public byte send_welcome_message { get; set; }
        public byte send_good_bye_message { get; set; }
        public System.DateTime last_modified { get; set; }
        public System.Guid id { get; set; }
        public Nullable<System.Guid> gd_by_template_id { get; set; }
        public string good_bye_message_subject { get; set; }
        public string good_bye_message_email_address { get; set; }
        public string default_subject_ { get; set; }
        public string default_reply_to_email_ { get; set; }
        public string default_from_name_ { get; set; }
        public string application_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_subscriber> sf_subscriber { get; set; }
    }
}
