//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_meta_types
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_meta_types()
        {
            this.sf_meta_types_section_names = new HashSet<sf_meta_types_section_names>();
        }
    
        public string section_captions_resource_type { get; set; }
        public Nullable<System.Guid> parent_type_id { get; set; }
        public string origin { get; set; }
        public string name_space { get; set; }
        public string module_name { get; set; }
        public byte is_dynamic { get; set; }
        public byte is_deleted { get; set; }
        public System.Guid id { get; set; }
        public int database_inheritance { get; set; }
        public string class_name { get; set; }
        public string base_class_name { get; set; }
        public string assembly_name { get; set; }
        public string app_name { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public short voa_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_meta_types_section_names> sf_meta_types_section_names { get; set; }
    }
}
