//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_mb_fields_backend_section
    {
        public string title { get; set; }
        public Nullable<System.Guid> parent_type_id { get; set; }
        public int ordinal { get; set; }
        public string nme { get; set; }
        public System.DateTime last_modified { get; set; }
        public byte is_expanded_by_default { get; set; }
        public byte is_expandable { get; set; }
        public System.Guid id { get; set; }
        public string expand_text { get; set; }
        public string application_name { get; set; }
        public short voa_version { get; set; }
    }
}
