//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_meta_type_descriptions
    {
        public string user_friendly_name { get; set; }
        public Nullable<System.Guid> meta_type_id { get; set; }
        public System.Guid id { get; set; }
        public string description { get; set; }
        public string app_name { get; set; }
        public short voa_version { get; set; }
    }
}
