//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_meta_index
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_meta_index()
        {
            this.sf_meta_index_composite_fields = new HashSet<sf_meta_index_composite_fields>();
        }
    
        public byte unque { get; set; }
        public string nme { get; set; }
        public Nullable<System.Guid> id2 { get; set; }
        public System.Guid id { get; set; }
        public byte clstered { get; set; }
        public short voa_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_meta_index_composite_fields> sf_meta_index_composite_fields { get; set; }
    }
}
