//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_mbl_frmt_templates
    {
        public byte use_custom_canonical_url { get; set; }
        public string template_name { get; set; }
        public Nullable<System.Guid> mbl_frmt_dfntn_id { get; set; }
        public Nullable<System.Guid> mbl_frmt_cntnt_type_id { get; set; }
        public string layout_template_name { get; set; }
        public System.DateTime last_modified { get; set; }
        public System.Guid id { get; set; }
        public string custom_canonical_url_format { get; set; }
        public string app_name { get; set; }
    }
}
