//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_media_file_urls
    {
        public string url { get; set; }
        public byte redirect_to_default { get; set; }
        public Nullable<System.Guid> media_file_link_id { get; set; }
        public Nullable<byte> is_default { get; set; }
        public System.Guid id { get; set; }
        public string app_name { get; set; }
    }
}
