//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_meta_attribute
    {
        public string val { get; set; }
        public string nme { get; set; }
        public System.Guid id { get; set; }
        public int voa_class { get; set; }
        public short voa_version { get; set; }
        public Nullable<System.Guid> id2 { get; set; }
    }
}
