//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_mb_dynamic_module_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_mb_dynamic_module_type()
        {
            this.sf_permissions = new HashSet<sf_permissions>();
        }
    
        public string type_namespace { get; set; }
        public string type_name { get; set; }
        public Nullable<System.Guid> parentTypeId { get; set; }
        public Nullable<System.Guid> parent_module_id { get; set; }
        public Nullable<System.Guid> pageId { get; set; }
        public string origin { get; set; }
        public string module_name { get; set; }
        public string main_short_text_field_name { get; set; }
        public System.DateTime last_modified { get; set; }
        public byte is_slf_referencing { get; set; }
        public byte inherits_permissions { get; set; }
        public System.Guid id { get; set; }
        public string display_name { get; set; }
        public byte check_field_permissions { get; set; }
        public byte can_inherit_permissions { get; set; }
        public string application_name { get; set; }
        public short voa_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_permissions> sf_permissions { get; set; }
    }
}
