//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_meta_fields
    {
        public string validation { get; set; }
        public string ui_hint { get; set; }
        public string title_ { get; set; }
        public string taxonomy_provider { get; set; }
        public Nullable<System.Guid> taxonomy_id { get; set; }
        public int storage_type { get; set; }
        public string sitefinity_type { get; set; }
        public string section_name { get; set; }
        public byte required { get; set; }
        public string regular_expression { get; set; }
        public Nullable<int> recommended_characters_count { get; set; }
        public int position_in_section { get; set; }
        public Nullable<System.Guid> type_id { get; set; }
        public string origin { get; set; }
        public string min_value { get; set; }
        public string max_value { get; set; }
        public int max_length { get; set; }
        public string linked_content_provider { get; set; }
        public byte two_way_content_link { get; set; }
        public byte is_single_taxon { get; set; }
        public byte is_protected_relation { get; set; }
        public Nullable<byte> is_localizable { get; set; }
        public byte is_internal { get; set; }
        public byte is_dynamic { get; set; }
        public byte is_deleted { get; set; }
        public Nullable<System.Guid> id2 { get; set; }
        public System.Guid id { get; set; }
        public byte hidden { get; set; }
        public string field_name { get; set; }
        public string display_format { get; set; }
        public string description_ { get; set; }
        public string default_value_expression { get; set; }
        public string default_value { get; set; }
        public byte default_fetch_group { get; set; }
        public string db_type { get; set; }
        public string db_sql_type { get; set; }
        public string db_scale { get; set; }
        public string db_length { get; set; }
        public string column_name { get; set; }
        public string clr_type { get; set; }
        public string choice_field_definition { get; set; }
        public string app_name { get; set; }
        public byte allow_multiple_relations { get; set; }
        public short voa_version { get; set; }
    }
}
