//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_media_file_links
    {
        public Nullable<int> width { get; set; }
        public Nullable<long> total_size { get; set; }
        public Nullable<int> number_of_chunks { get; set; }
        public string mime_type { get; set; }
        public Nullable<System.Guid> content_id { get; set; }
        public System.Guid id { get; set; }
        public Nullable<int> height { get; set; }
        public string file_path { get; set; }
        public Nullable<System.Guid> file_id { get; set; }
        public string extension { get; set; }
        public string default_url { get; set; }
        public int culture { get; set; }
        public Nullable<int> chunk_size { get; set; }
        public string app_name { get; set; }
    }
}
