//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_mb_dynamic_module_field
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_mb_dynamic_module_field()
        {
            this.sf_permissions = new HashSet<sf_permissions>();
        }
    
        public string widget_type_name { get; set; }
        public int video_max_size { get; set; }
        public string video_extensions { get; set; }
        public string type_u_i_name { get; set; }
        public string title { get; set; }
        public int special_type { get; set; }
        public byte show_in_grid { get; set; }
        public string related_data_type { get; set; }
        public string related_data_provider { get; set; }
        public string regular_expression { get; set; }
        public Nullable<int> recommended_characters_count { get; set; }
        public Nullable<System.Guid> parent_type_id { get; set; }
        public Nullable<System.Guid> parent_section_id { get; set; }
        public string origin { get; set; }
        public int ordinal { get; set; }
        public string number_unit { get; set; }
        public string nme { get; set; }
        public string module_name { get; set; }
        public string min_number_range { get; set; }
        public int min_length { get; set; }
        public string media_type { get; set; }
        public string max_number_range { get; set; }
        public int max_length { get; set; }
        public string length_validation_message { get; set; }
        public System.DateTime last_modified { get; set; }
        public byte is_transient { get; set; }
        public byte is_rquired_to_select_ddl_value { get; set; }
        public byte is_required_to_select_checkbox { get; set; }
        public byte is_required { get; set; }
        public byte is_localizable { get; set; }
        public byte is_hidden_field { get; set; }
        public string instructional_text { get; set; }
        public string instructional_choice { get; set; }
        public byte inherits_permissions { get; set; }
        public byte include_in_indexes { get; set; }
        public int image_max_size { get; set; }
        public string image_extensions { get; set; }
        public System.Guid id { get; set; }
        public int grid_column_ordinal { get; set; }
        public string frontend_widget_type_name { get; set; }
        public string frontend_widget_label { get; set; }
        public int file_max_size { get; set; }
        public string file_extensions { get; set; }
        public int field_type { get; set; }
        public string field_namespace { get; set; }
        public byte disable_link_parser { get; set; }
        public string default_value { get; set; }
        public int decimal_places_count { get; set; }
        public int ddl_choice_default_value_index { get; set; }
        public string d_b_type { get; set; }
        public string d_b_length { get; set; }
        public string column_name { get; set; }
        public Nullable<System.Guid> classification_id { get; set; }
        public string choices { get; set; }
        public string choice_render_type { get; set; }
        public byte checked_by_default { get; set; }
        public byte can_select_multiple_items { get; set; }
        public byte can_inherit_permissions { get; set; }
        public byte cn_crate_items_while_selecting { get; set; }
        public string application_name { get; set; }
        public byte allow_nulls { get; set; }
        public byte allow_multiple_videos { get; set; }
        public byte allow_multiple_images { get; set; }
        public byte allow_multiple_files { get; set; }
        public byte allow_image_library { get; set; }
        public int address_field_mode { get; set; }
        public short voa_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_permissions> sf_permissions { get; set; }
    }
}
