//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_media_thumbnails
    {
        public Nullable<int> width { get; set; }
        public int typ { get; set; }
        public long total_size { get; set; }
        public Nullable<System.Guid> content_id { get; set; }
        public string nme { get; set; }
        public string mime_type { get; set; }
        public System.Guid id { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<System.Guid> file_id { get; set; }
        public byte[] dta { get; set; }
        public string culture { get; set; }
        public byte uploaded { get; set; }
        public int number_of_chunks { get; set; }
        public int chunk_size { get; set; }
        public short voa_version { get; set; }
    }
}
