//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_notif_msg_job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_notif_msg_job()
        {
            this.sf_ntf_msg_jb_cstm_mssg_haders = new HashSet<sf_ntf_msg_jb_cstm_mssg_haders>();
            this.sf_ntf_msg_jb_xcldd_rslvd_kys_ = new HashSet<sf_ntf_msg_jb_xcldd_rslvd_kys_>();
        }
    
        public Nullable<System.Guid> subsription_list_id { get; set; }
        public string sender_profile_name { get; set; }
        public string sender_name { get; set; }
        public string sender_address { get; set; }
        public string module_name { get; set; }
        public Nullable<System.Guid> message_template_id { get; set; }
        public Nullable<System.DateTime> last_activity_date { get; set; }
        public int job_status { get; set; }
        public System.Guid id { get; set; }
        public string failure_description { get; set; }
        public string description { get; set; }
        public byte clear_subscription_data { get; set; }
        public string account_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_ntf_msg_jb_cstm_mssg_haders> sf_ntf_msg_jb_cstm_mssg_haders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_ntf_msg_jb_xcldd_rslvd_kys_> sf_ntf_msg_jb_xcldd_rslvd_kys_ { get; set; }
    }
}
