//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_notif_msg_template
    {
        public string sender_name { get; set; }
        public string sender_email { get; set; }
        public string subject { get; set; }
        public string resolve_key { get; set; }
        public string plain_text_version { get; set; }
        public string module_name { get; set; }
        public Nullable<System.Guid> last_modified_by_id { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public System.Guid id { get; set; }
        public string body_html { get; set; }
        public string account_name { get; set; }
    }
}
