//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_ntf_msg_jb_cstm_mssg_haders
    {
        public System.Guid id { get; set; }
        public string mapkey { get; set; }
        public string val { get; set; }
    
        public virtual sf_notif_msg_job sf_notif_msg_job { get; set; }
    }
}
