//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_notif_subscribers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_notif_subscribers()
        {
            this.sf_ntf_sbscrbrs_cstm_prperties = new HashSet<sf_ntf_sbscrbrs_cstm_prperties>();
        }
    
        public string resolve_key { get; set; }
        public string module_name { get; set; }
        public string last_name { get; set; }
        public System.Guid id { get; set; }
        public string first_name { get; set; }
        public string email { get; set; }
        public byte disabled { get; set; }
        public string account_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_ntf_sbscrbrs_cstm_prperties> sf_ntf_sbscrbrs_cstm_prperties { get; set; }
    }
}
