//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_notif_subscr_list
    {
        public string title { get; set; }
        public string resolve_key { get; set; }
        public string module_name { get; set; }
        public System.Guid id { get; set; }
        public string description { get; set; }
        public string account_name { get; set; }
    }
}
