//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_notif_cmplt_msg_job
    {
        public int sf_notif_cmplt_msg_job_id { get; set; }
        public Nullable<int> total_delivery_subscribers { get; set; }
        public System.DateTime timeStarted { get; set; }
        public System.DateTime timeCompleted { get; set; }
        public string module_name { get; set; }
        public Nullable<System.Guid> id { get; set; }
        public string description { get; set; }
        public string account_name { get; set; }
    }
}
