//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_ocd_itms
    {
        public string url { get; set; }
        public int status { get; set; }
        public string site_map_node_key { get; set; }
        public Nullable<System.Guid> site_id { get; set; }
        public int priority { get; set; }
        public string lang { get; set; }
        public string key { get; set; }
        public string host { get; set; }
        public string e_tag { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public string cacheVaryKey { get; set; }
        public short voa_version { get; set; }
    }
}
