//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_open_stat
    {
        public int sf_open_stat_id { get; set; }
        public System.Guid subscriber_id { get; set; }
        public System.DateTime opened_date { get; set; }
        public System.Guid campaign_id { get; set; }
        public short voa_version { get; set; }
    }
}
