//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_pckgng_addns_stts
    {
        public Nullable<int> strctr_stts { get; set; }
        public System.Guid site_id { get; set; }
        public Nullable<int> dta_stts { get; set; }
        public System.Guid addn_id { get; set; }
    }
}
