//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_pckgng_addns_err_stts
    {
        public byte has_errs_on_strctr_imprt { get; set; }
        public byte has_errs_on_cntnt_imprt { get; set; }
        public byte has_errs_on_actvt { get; set; }
        public System.Guid addn_id { get; set; }
    }
}
