//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_prs_crtr_grp_sf_prs_crtrion
    {
        public int sf_prs_criteria_group_id { get; set; }
        public int seq { get; set; }
        public Nullable<int> sf_prs_criterion_id { get; set; }
    
        public virtual sf_prs_criteria_group sf_prs_criteria_group { get; set; }
        public virtual sf_prs_criterion sf_prs_criterion { get; set; }
    }
}
