//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_pckgng_addns
    {
        public string version { get; set; }
        public string name { get; set; }
        public System.Guid addn_id { get; set; }
        public string description { get; set; }
        public string author { get; set; }
        public string addn_key { get; set; }
    }
}
