//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_page_templates
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_page_templates()
        {
            this.sf_pg_tmplts_pblshd_trnsltions = new HashSet<sf_pg_tmplts_pblshd_trnsltions>();
            this.sf_pg_tmpltes_sf_language_data = new HashSet<sf_pg_tmpltes_sf_language_data>();
            this.sf_permissions = new HashSet<sf_permissions>();
        }
    
        public string theme { get; set; }
        public int view_state_encryption { get; set; }
        public int vrsion { get; set; }
        public byte validate_request { get; set; }
        public string ui_culture { get; set; }
        public string title_ { get; set; }
        public string template_name { get; set; }
        public byte smart_navigation { get; set; }
        public byte sliding_expiration { get; set; }
        public byte show_in_navigation { get; set; }
        public string response_encoding { get; set; }
        public byte require_ssl { get; set; }
        public string renderer { get; set; }
        public Nullable<System.Guid> personalization_segment_id { get; set; }
        public Nullable<System.Guid> personalization_master_id { get; set; }
        public Nullable<System.Guid> prent_template_id { get; set; }
        public Nullable<System.Guid> ownr { get; set; }
        public short ordinal { get; set; }
        public string nme { get; set; }
        public string master_page { get; set; }
        public byte maintain_scroll { get; set; }
        public Nullable<System.Guid> locked_by { get; set; }
        public Nullable<System.Guid> last_modified_by { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public int last_control_id { get; set; }
        public string keywords_ { get; set; }
        public string ky { get; set; }
        public byte is_personalized { get; set; }
        public byte inherits_permissions { get; set; }
        public byte include_script_manger { get; set; }
        public System.Guid id { get; set; }
        public Nullable<int> framework { get; set; }
        public string error_page { get; set; }
        public byte enable_view_state_mac { get; set; }
        public byte enable_view_state { get; set; }
        public byte enable_theming { get; set; }
        public byte enable_session_state { get; set; }
        public byte enable_event_validation { get; set; }
        public string description_ { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string culture { get; set; }
        public Nullable<System.Guid> category { get; set; }
        public byte can_inherit_permissions { get; set; }
        public byte cache_output { get; set; }
        public int cache_duration { get; set; }
        public byte buffer_output { get; set; }
        public string app_name { get; set; }
        public short voa_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_pg_tmplts_pblshd_trnsltions> sf_pg_tmplts_pblshd_trnsltions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_pg_tmpltes_sf_language_data> sf_pg_tmpltes_sf_language_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_permissions> sf_permissions { get; set; }
    }
}
