//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_permissions_inheritance_map
    {
        public int sf_prmssons_inheritance_map_id { get; set; }
        public Nullable<System.Guid> object_id { get; set; }
        public string child_object_type_name { get; set; }
        public Nullable<System.Guid> child_object_id { get; set; }
    }
}
