//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_publishing_pipe_settings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_publishing_pipe_settings()
        {
            this.sf_pblshng_pp_sttngs_cntnt_lnk = new HashSet<sf_pblshng_pp_sttngs_cntnt_lnk>();
            this.sf_pblshng_pp_sttngs_ddtnl_dta = new HashSet<sf_pblshng_pp_sttngs_ddtnl_dta>();
            this.sf_pblshng_pp_sttngs_lngge_ids = new HashSet<sf_pblshng_pp_sttngs_lngge_ids>();
        }
    
        public string ui_name { get; set; }
        public string title { get; set; }
        public int schedule_type { get; set; }
        public Nullable<System.DateTime> schedule_time { get; set; }
        public int schedule_day { get; set; }
        public string resource_class_id { get; set; }
        public Nullable<System.Guid> id3 { get; set; }
        public string pipe_name { get; set; }
        public int max_items { get; set; }
        public Nullable<System.Guid> id2 { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public byte is_inbound { get; set; }
        public byte is_active { get; set; }
        public int invocation_mode { get; set; }
        public System.Guid id { get; set; }
        public string filter_expression { get; set; }
        public string description { get; set; }
        public string application_name { get; set; }
        public int voa_class { get; set; }
        public short voa_version { get; set; }
        public string pop3_user_name { get; set; }
        public string pop3_server { get; set; }
        public Nullable<int> pop3_port { get; set; }
        public string pop3_password { get; set; }
        public Nullable<byte> is_ssl_connection { get; set; }
        public string user_name_reference { get; set; }
        public string search_pattern { get; set; }
        public string app_name_reference { get; set; }
        public string url_name { get; set; }
        public Nullable<int> output_settings { get; set; }
        public Nullable<int> format_settings { get; set; }
        public Nullable<int> content_size { get; set; }
        public string search_provider_name { get; set; }
        public string catalog_name { get; set; }
        public string provider_name { get; set; }
        public Nullable<System.Guid> imported_item_parent_id { get; set; }
        public Nullable<byte> import_item_as_published { get; set; }
        public string content_type_name { get; set; }
        public Nullable<System.Guid> back_links_page_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_pblshng_pp_sttngs_cntnt_lnk> sf_pblshng_pp_sttngs_cntnt_lnk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_pblshng_pp_sttngs_ddtnl_dta> sf_pblshng_pp_sttngs_ddtnl_dta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_pblshng_pp_sttngs_lngge_ids> sf_pblshng_pp_sttngs_lngge_ids { get; set; }
    }
}
