//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_page_node
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_page_node()
        {
            this.sf_pg_nd_prmssnst_bjct_ttl_rs_ = new HashSet<sf_pg_nd_prmssnst_bjct_ttl_rs_>();
            this.sf_page_node_attrbutes = new HashSet<sf_page_node_attrbutes>();
            this.sf_permissions = new HashSet<sf_permissions>();
        }
    
        public string url_name_ { get; set; }
        public string title_ { get; set; }
        public byte show_in_navigation { get; set; }
        public Nullable<System.Guid> root_id { get; set; }
        public byte require_ssl { get; set; }
        public byte render_as_link { get; set; }
        public string redirect_url_ { get; set; }
        public float priority { get; set; }
        public Nullable<System.Guid> previous_parent_id { get; set; }
        public Nullable<System.Guid> parent_id { get; set; }
        public Nullable<System.Guid> content_id { get; set; }
        public Nullable<System.Guid> ownr { get; set; }
        public float ordinal { get; set; }
        public byte open_new_window { get; set; }
        public int node_type { get; set; }
        public string nme { get; set; }
        public string module_name { get; set; }
        public short loc_strtgy { get; set; }
        public string linked_node_provider { get; set; }
        public Nullable<System.Guid> linked_node_id { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public byte is_deleted { get; set; }
        public byte inherits_permissions { get; set; }
        public byte inc_in_srch_idx { get; set; }
        public System.Guid id { get; set; }
        public string extension { get; set; }
        public Nullable<byte> enable_default_canonical_url { get; set; }
        public string description_ { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public byte crawlable { get; set; }
        public byte can_inherit_permissions { get; set; }
        public string approval_workflow_state_ { get; set; }
        public string app_name { get; set; }
        public byte allow_parameters_validation { get; set; }
        public byte allow_multiple_urls { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_pg_nd_prmssnst_bjct_ttl_rs_> sf_pg_nd_prmssnst_bjct_ttl_rs_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_page_node_attrbutes> sf_page_node_attrbutes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_permissions> sf_permissions { get; set; }
    }
}
