//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_prs_segment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_prs_segment()
        {
            this.sf_prs_sgmnt_sf_prs_crtr_group = new HashSet<sf_prs_sgmnt_sf_prs_crtr_group>();
        }
    
        public string type { get; set; }
        public Nullable<System.Guid> site_id { get; set; }
        public int priority { get; set; }
        public string nme { get; set; }
        public System.DateTime last_modified { get; set; }
        public byte is_active { get; set; }
        public System.Guid id { get; set; }
        public string description { get; set; }
        public string app_name { get; set; }
        public short voa_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_prs_sgmnt_sf_prs_crtr_group> sf_prs_sgmnt_sf_prs_crtr_group { get; set; }
    }
}
