//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_publishing_point
    {
        public string storage_type_name { get; set; }
        public string storage_item_provider_name { get; set; }
        public Nullable<System.Guid> id2 { get; set; }
        public string pblshng_pnt_bsness_object_name { get; set; }
        public Nullable<System.Guid> ownr { get; set; }
        public string nme { get; set; }
        public Nullable<System.DateTime> last_publication_date { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public Nullable<byte> is_template { get; set; }
        public byte is_shared_with_all_sites { get; set; }
        public byte is_active { get; set; }
        public string inbound_pipes_template { get; set; }
        public System.Guid id { get; set; }
        public string description_ { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string application_name { get; set; }
        public short voa_version { get; set; }
    }
}
