//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_presentation_data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_presentation_data()
        {
            this.sf_frm_dscrptn_sf_prsnttn_data = new HashSet<sf_frm_dscrptn_sf_prsnttn_data>();
        }
    
        public string theme { get; set; }
        public string resource_assembly_name { get; set; }
        public Nullable<System.Guid> ownr { get; set; }
        public string nme { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public System.Guid id { get; set; }
        public string embedded_template_name { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string data_type { get; set; }
        public string dta { get; set; }
        public string app_name { get; set; }
        public int voa_class { get; set; }
        public short voa_version { get; set; }
        public string resource_class_id { get; set; }
        public string name_for_developers { get; set; }
        public Nullable<byte> is_different_from_embedded { get; set; }
        public string friendly_control_name { get; set; }
        public string control_type { get; set; }
        public Nullable<System.Guid> item_id { get; set; }
        public string condition { get; set; }
        public string area_name { get; set; }
        public Nullable<System.Guid> id3 { get; set; }
        public Nullable<System.Guid> id4 { get; set; }
        public Nullable<System.Guid> id2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_frm_dscrptn_sf_prsnttn_data> sf_frm_dscrptn_sf_prsnttn_data { get; set; }
    }
}
