//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_permissions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_permissions()
        {
            this.sf_sites_sf_permissions = new HashSet<sf_sites_sf_permissions>();
            this.sf_blog_posts = new HashSet<sf_blog_posts>();
            this.sf_blogs = new HashSet<sf_blogs>();
            this.sf_content_items = new HashSet<sf_content_items>();
            this.sf_dynamic_content = new HashSet<sf_dynamic_content>();
            this.sf_events = new HashSet<sf_events>();
            this.sf_forum_groups = new HashSet<sf_forum_groups>();
            this.sf_forums = new HashSet<sf_forums>();
            this.sf_form_description = new HashSet<sf_form_description>();
            this.sf_libraries = new HashSet<sf_libraries>();
            this.sf_list_items = new HashSet<sf_list_items>();
            this.sf_lists = new HashSet<sf_lists>();
            this.sf_mb_dnc_cnt_provider = new HashSet<sf_mb_dnc_cnt_provider>();
            this.sf_mb_dynamic_module_field = new HashSet<sf_mb_dynamic_module_field>();
            this.sf_mb_dynamic_module = new HashSet<sf_mb_dynamic_module>();
            this.sf_mb_dynamic_module_type = new HashSet<sf_mb_dynamic_module_type>();
            this.sf_media_content = new HashSet<sf_media_content>();
            this.sf_news_items = new HashSet<sf_news_items>();
            this.sf_object_data = new HashSet<sf_object_data>();
            this.sf_page_node = new HashSet<sf_page_node>();
            this.sf_page_templates = new HashSet<sf_page_templates>();
            this.sf_security_roots = new HashSet<sf_security_roots>();
            this.sf_taxonomies = new HashSet<sf_taxonomies>();
            this.sf_wfl_definition = new HashSet<sf_wfl_definition>();
        }
    
        public string set_name { get; set; }
        public System.Guid principal_id { get; set; }
        public System.Guid object_id { get; set; }
        public System.DateTime last_modified { get; set; }
        public System.Guid id { get; set; }
        public int grnt { get; set; }
        public int deny { get; set; }
        public string app_name { get; set; }
        public short voa_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_sites_sf_permissions> sf_sites_sf_permissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_blog_posts> sf_blog_posts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_blogs> sf_blogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_content_items> sf_content_items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_dynamic_content> sf_dynamic_content { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_events> sf_events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_forum_groups> sf_forum_groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_forums> sf_forums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_form_description> sf_form_description { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_libraries> sf_libraries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_list_items> sf_list_items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_lists> sf_lists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_mb_dnc_cnt_provider> sf_mb_dnc_cnt_provider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_mb_dynamic_module_field> sf_mb_dynamic_module_field { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_mb_dynamic_module> sf_mb_dynamic_module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_mb_dynamic_module_type> sf_mb_dynamic_module_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_media_content> sf_media_content { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_news_items> sf_news_items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_object_data> sf_object_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_page_node> sf_page_node { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_page_templates> sf_page_templates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_security_roots> sf_security_roots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_taxonomies> sf_taxonomies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_wfl_definition> sf_wfl_definition { get; set; }
    }
}
