//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_pipe_mapping_translation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_pipe_mapping_translation()
        {
            this.sf_pblshng_mppng_sf_pp_mppng_t = new HashSet<sf_pblshng_mppng_sf_pp_mppng_t>();
        }
    
        public string translator_settings { get; set; }
        public string translator_name { get; set; }
        public System.Guid id { get; set; }
        public string application_name { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public short voa_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_pblshng_mppng_sf_pp_mppng_t> sf_pblshng_mppng_sf_pp_mppng_t { get; set; }
    }
}
