//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_page_data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_page_data()
        {
            this.sf_pg_dt_pblished_translations = new HashSet<sf_pg_dt_pblished_translations>();
            this.sf_page_data_sf_language_data = new HashSet<sf_page_data_sf_language_data>();
            this.sf_page_data_attrbutes = new HashSet<sf_page_data_attrbutes>();
        }
    
        public string theme { get; set; }
        public decimal votes_sum { get; set; }
        public long votes_count { get; set; }
        public byte visible { get; set; }
        public int views_count { get; set; }
        public int view_state_encryption { get; set; }
        public int vrsion { get; set; }
        public string variation_type_key { get; set; }
        public byte validate_request { get; set; }
        public int url_evaluation_mode { get; set; }
        public int trace_mode { get; set; }
        public byte trace { get; set; }
        public string template_name { get; set; }
        public Nullable<System.Guid> template_id { get; set; }
        public int status { get; set; }
        public string source_key { get; set; }
        public string response_encoding { get; set; }
        public string renderer { get; set; }
        public System.DateTime publication_date { get; set; }
        public Nullable<System.Guid> personalization_segment_id { get; set; }
        public Nullable<System.Guid> personalization_master_id { get; set; }
        public Nullable<System.Guid> ownr { get; set; }
        public string cache_profile { get; set; }
        public Nullable<System.Guid> page_node_id { get; set; }
        public string master_page { get; set; }
        public byte maintain_scroll { get; set; }
        public Nullable<System.Guid> locked_by { get; set; }
        public Nullable<System.Guid> last_modified_by { get; set; }
        public System.DateTime last_modified { get; set; }
        public int last_control_id { get; set; }
        public string keywords_ { get; set; }
        public byte is_personalized { get; set; }
        public byte is_auto_created { get; set; }
        public byte include_script_manger { get; set; }
        public System.Guid content_id { get; set; }
        public string html_title_ { get; set; }
        public string head_tag_content { get; set; }
        public int flags { get; set; }
        public string external_page { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public string error_page { get; set; }
        public byte enable_view_state_mac { get; set; }
        public byte enable_view_state { get; set; }
        public byte enable_theming { get; set; }
        public byte enable_session_state { get; set; }
        public byte enable_event_validation { get; set; }
        public string description_ { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string culture { get; set; }
        public string content_state { get; set; }
        public int comments_count { get; set; }
        public string code_behind_type { get; set; }
        public int build_stamp { get; set; }
        public byte buffer_output { get; set; }
        public string app_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_pg_dt_pblished_translations> sf_pg_dt_pblished_translations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_page_data_sf_language_data> sf_page_data_sf_language_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_page_data_attrbutes> sf_page_data_attrbutes { get; set; }
    }
}
