//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_pckgng_addn_lnks
    {
        public string itm_type { get; set; }
        public string itm_prvdr { get; set; }
        public Nullable<System.Guid> itm_id { get; set; }
        public System.Guid id { get; set; }
        public Nullable<System.Guid> addn_id { get; set; }
        public string addtnl_info { get; set; }
    }
}
