//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_pblshng_mppng_sf_pp_mppng_t
    {
        public System.Guid id { get; set; }
        public int seq { get; set; }
        public Nullable<System.Guid> id2 { get; set; }
    
        public virtual sf_publishing_mapping sf_publishing_mapping { get; set; }
        public virtual sf_pipe_mapping_translation sf_pipe_mapping_translation { get; set; }
    }
}
