//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_rdsgn_media_query
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_rdsgn_media_query()
        {
            this.sf_rdsgn_media_query_link = new HashSet<sf_rdsgn_media_query_link>();
        }
    
        public string nme { get; set; }
        public Nullable<System.Guid> mini_site_page_id { get; set; }
        public string layout_transformations_j_s_o_n { get; set; }
        public System.DateTime last_modified { get; set; }
        public byte is_active { get; set; }
        public System.Guid id { get; set; }
        public int behavior { get; set; }
        public string application_name { get; set; }
        public string additional_css_file_path { get; set; }
        public short voa_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_rdsgn_media_query_link> sf_rdsgn_media_query_link { get; set; }
    }
}
