//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_rdsgn_media_query_link
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_rdsgn_media_query_link()
        {
            this.sf_rdsgn_media_query = new HashSet<sf_rdsgn_media_query>();
        }
    
        public int link_type { get; set; }
        public System.DateTime last_modified { get; set; }
        public string item_type { get; set; }
        public Nullable<System.Guid> item_id { get; set; }
        public System.Guid id { get; set; }
        public string application_name { get; set; }
        public short voa_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_rdsgn_media_query> sf_rdsgn_media_query { get; set; }
    }
}
