//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_rbin_item
    {
        public Nullable<System.Guid> owner { get; set; }
        public System.DateTime last_modified { get; set; }
        public System.Guid id { get; set; }
        public string del_item_wrkfl_status { get; set; }
        public string del_item_type_name { get; set; }
        public string del_item_title { get; set; }
        public Nullable<System.Guid> del_item_site_id { get; set; }
        public string del_item_prvdr_name { get; set; }
        public string del_item_parent_type_name { get; set; }
        public string del_item_titles_path { get; set; }
        public string del_item_lang { get; set; }
        public Nullable<System.Guid> del_item_id { get; set; }
        public System.DateTime date_created { get; set; }
        public string app_name { get; set; }
        public short voa_version { get; set; }
    }
}
