//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_rdsgn_media_query_rule
    {
        public int width_type { get; set; }
        public string resulting_rule { get; set; }
        public string resolution { get; set; }
        public Nullable<System.Guid> parent_media_query_id { get; set; }
        public int orientation { get; set; }
        public string min_width { get; set; }
        public string min_height { get; set; }
        public string max_width { get; set; }
        public string max_height { get; set; }
        public System.DateTime last_modified { get; set; }
        public byte is_monochrome { get; set; }
        public byte is_manual_media_query { get; set; }
        public byte is_grid { get; set; }
        public System.Guid id { get; set; }
        public int height_type { get; set; }
        public string exact_width { get; set; }
        public string exact_height { get; set; }
        public string device_type_name { get; set; }
        public string description { get; set; }
        public string aspect_ratio { get; set; }
        public string application_name { get; set; }
        public short voa_version { get; set; }
    }
}
