//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_site_item_links
    {
        public System.Guid site_id { get; set; }
        public string item_type { get; set; }
        public System.Guid item_id { get; set; }
        public string application_name { get; set; }
        public short voa_version { get; set; }
    }
}
