//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_sitefinity_profile
    {
        public System.Guid id { get; set; }
        public string preferred_language { get; set; }
        public string preferences { get; set; }
        public string nickname { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string about { get; set; }
        public Nullable<int> posts_count { get; set; }
        public Nullable<bool> is_profile_public { get; set; }
    
        public virtual sf_user_profile sf_user_profile { get; set; }
    }
}
