//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_site_data_src
    {
        public string title { get; set; }
        public string provider { get; set; }
        public System.Guid owner_site_id { get; set; }
        public string nme { get; set; }
        public System.Guid id { get; set; }
    }
}
