//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_subscription_info
    {
        public int sf_subscription_info_id { get; set; }
        public Nullable<System.Guid> subscription_list_id { get; set; }
        public System.DateTime subscription_date { get; set; }
        public Nullable<System.Guid> id2 { get; set; }
        public System.DateTime last_modified { get; set; }
        public Nullable<System.Guid> id { get; set; }
        public string application_name { get; set; }
        public short voa_version { get; set; }
    }
}
