//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_schema_vrsns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_schema_vrsns()
        {
            this.sf_schema_vrsns_meta_types = new HashSet<sf_schema_vrsns_meta_types>();
        }
    
        public int version_number { get; set; }
        public int previous_version_number { get; set; }
        public string module_name { get; set; }
        public byte meta_data_changed { get; set; }
        public System.DateTime last_upgrade_date { get; set; }
        public System.Guid id { get; set; }
        public string cultures { get; set; }
        public string connection_id { get; set; }
        public string connection_hash { get; set; }
        public string assembly { get; set; }
        public string app_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_schema_vrsns_meta_types> sf_schema_vrsns_meta_types { get; set; }
    }
}
