//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_sites
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_sites()
        {
            this.sf_sites_culture_keys = new HashSet<sf_sites_culture_keys>();
            this.sf_sites_domain_aliases = new HashSet<sf_sites_domain_aliases>();
            this.sf_sites_sf_permissions = new HashSet<sf_sites_sf_permissions>();
        }
    
        public string staging_url { get; set; }
        public Nullable<System.Guid> site_map_root_node_id { get; set; }
        public int site_configuration_mode { get; set; }
        public bool requires_ssl { get; set; }
        public bool redirectIfOffline { get; set; }
        public Nullable<System.Guid> ownr { get; set; }
        public string offlineSiteMessage { get; set; }
        public Nullable<System.Guid> offlinePageToRedirect { get; set; }
        public string nme { get; set; }
        public string live_url { get; set; }
        public bool is_offline { get; set; }
        public bool isLocatedInMainMenu { get; set; }
        public byte is_default { get; set; }
        public byte inherits_permissions { get; set; }
        public System.Guid id { get; set; }
        public Nullable<System.Guid> home_page_id { get; set; }
        public string front_end_login_page_url { get; set; }
        public Nullable<System.Guid> front_end_login_page_id { get; set; }
        public Nullable<System.Guid> default_frontend_template_id { get; set; }
        public string default_culture_key { get; set; }
        public byte can_inherit_permissions { get; set; }
        public string application_name { get; set; }
        public short voa_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_sites_culture_keys> sf_sites_culture_keys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_sites_domain_aliases> sf_sites_domain_aliases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_sites_sf_permissions> sf_sites_sf_permissions { get; set; }
    }
}
