//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_scheduled_tasks
    {
        public string type_of_schedule { get; set; }
        public string title { get; set; }
        public string task_name { get; set; }
        public string task_data { get; set; }
        public Nullable<System.Guid> subscr_lst_id { get; set; }
        public string status_message { get; set; }
        public int status { get; set; }
        public Nullable<System.Guid> siteId { get; set; }
        public string schedule_data { get; set; }
        public int progress { get; set; }
        public Nullable<System.Guid> owner { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public Nullable<System.DateTime> last_executed_time { get; set; }
        public string language { get; set; }
        public string ky { get; set; }
        public byte is_system { get; set; }
        public byte is_running { get; set; }
        public byte is_recurring { get; set; }
        public string instance_name { get; set; }
        public System.Guid id { get; set; }
        public System.DateTime execute_time { get; set; }
        public byte enabled { get; set; }
        public string description { get; set; }
        public string concurrent_tasks_key { get; set; }
        public string application_name { get; set; }
        public short voa_version { get; set; }
    }
}
