//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_stat_sentence
    {
        public string verb { get; set; }
        public System.DateTime time_stamp { get; set; }
        public string subject_type { get; set; }
        public string subject_string_meta_field5 { get; set; }
        public string subject_string_meta_field4 { get; set; }
        public string subject_string_meta_field3 { get; set; }
        public string subject_string_meta_field2 { get; set; }
        public string subject_string_meta_field1 { get; set; }
        public string subject_provider { get; set; }
        public string subject_key { get; set; }
        public int subject_int_meta_field { get; set; }
        public Nullable<System.Guid> subject_id { get; set; }
        public double subject_double_meta_field { get; set; }
        public decimal subject_decimal_meta_field { get; set; }
        public System.DateTime subject_date_time_meta_field { get; set; }
        public byte subject_bool_meta_field { get; set; }
        public string object_type { get; set; }
        public string object_string_meta_field5 { get; set; }
        public string object_string_meta_field4 { get; set; }
        public string object_string_meta_field3 { get; set; }
        public string object_string_meta_field2 { get; set; }
        public string object_string_meta_field1 { get; set; }
        public string object_provider { get; set; }
        public string object_key { get; set; }
        public int object_int_meta_field { get; set; }
        public Nullable<System.Guid> object_id { get; set; }
        public double object_double_meta_field { get; set; }
        public decimal object_decimal_meta_field { get; set; }
        public System.DateTime object_date_time_meta_field { get; set; }
        public byte object_bool_meta_field { get; set; }
        public long id { get; set; }
    }
}
