//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_site_data_src_lnks
    {
        public Nullable<System.Guid> site_id { get; set; }
        public bool is_default { get; set; }
        public System.Guid id { get; set; }
        public System.Guid data_source_id { get; set; }
    }
}
