//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_tr_jbs
    {
        public string trg_langs { get; set; }
        public Nullable<System.Guid> prjc_id { get; set; }
        public System.Guid id { get; set; }
        public System.DateTime date_created { get; set; }
    }
}
