//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_taxa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_taxa()
        {
            this.sf_taxa_attrbutes = new HashSet<sf_taxa_attrbutes>();
            this.sf_taxonomies = new HashSet<sf_taxonomies>();
            this.sf_taxa1 = new HashSet<sf_taxa>();
            this.sf_taxa2 = new HashSet<sf_taxa>();
            this.sf_taxa11 = new HashSet<sf_taxa>();
            this.sf_taxa3 = new HashSet<sf_taxa>();
        }
    
        public string url_name_ { get; set; }
        public string title_ { get; set; }
        public Nullable<System.Guid> taxonomy_id { get; set; }
        public int status { get; set; }
        public byte show_in_navigation { get; set; }
        public byte render_as_link { get; set; }
        public float ordinal { get; set; }
        public string nme { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public System.Guid id { get; set; }
        public string description_ { get; set; }
        public string app_name { get; set; }
        public int voa_class { get; set; }
        public short voa_version { get; set; }
        public Nullable<System.Guid> fct_txn_fct_tx_id { get; set; }
        public Nullable<System.Guid> parent_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_taxa_attrbutes> sf_taxa_attrbutes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_taxonomies> sf_taxonomies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_taxa> sf_taxa1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_taxa> sf_taxa2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_taxa> sf_taxa11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_taxa> sf_taxa3 { get; set; }
    }
}
