//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_tr_sources
    {
        public string title { get; set; }
        public string src_lang { get; set; }
        public Nullable<System.Guid> site_id { get; set; }
        public string root_key { get; set; }
        public Nullable<System.Guid> parnt_id { get; set; }
        public string item_type { get; set; }
        public string item_prvdr { get; set; }
        public Nullable<System.Guid> item_id { get; set; }
        public System.Guid id { get; set; }
    }
}
