//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_taxonomies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_taxonomies()
        {
            this.sf_txnms_prmssnst_bjct_ttl_rs_ = new HashSet<sf_txnms_prmssnst_bjct_ttl_rs_>();
            this.sf_txnms_spprtd_prmission_sets = new HashSet<sf_txnms_spprtd_prmission_sets>();
            this.sf_taxa = new HashSet<sf_taxa>();
            this.sf_permissions = new HashSet<sf_permissions>();
        }
    
        public string title_ { get; set; }
        public string taxon_name_ { get; set; }
        public Nullable<System.Guid> root_id { get; set; }
        public Nullable<System.Guid> ownr { get; set; }
        public string nme { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public byte inherits_permissions { get; set; }
        public System.Guid id { get; set; }
        public string description_ { get; set; }
        public byte can_inherit_permissions { get; set; }
        public string app_name { get; set; }
        public int voa_class { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_txnms_prmssnst_bjct_ttl_rs_> sf_txnms_prmssnst_bjct_ttl_rs_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_txnms_spprtd_prmission_sets> sf_txnms_spprtd_prmission_sets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_taxa> sf_taxa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_permissions> sf_permissions { get; set; }
    }
}
