//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_tr_units
    {
        public Nullable<System.Guid> trns_id { get; set; }
        public string title { get; set; }
        public string trg_val { get; set; }
        public string src_val { get; set; }
        public string prop_name { get; set; }
        public float ordinal { get; set; }
        public System.Guid id { get; set; }
    }
}
