//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_tr_trnsltns
    {
        public string unique_item_key { get; set; }
        public int trns_status { get; set; }
        public string trg_lang { get; set; }
        public int src_vrsn_type { get; set; }
        public Nullable<System.Guid> tr_source_id { get; set; }
        public Nullable<System.Guid> owner { get; set; }
        public string metadata { get; set; }
        public Nullable<System.Guid> job_id { get; set; }
        public System.Guid id { get; set; }
        public string ext_status { get; set; }
        public string external_id { get; set; }
        public string err_msg { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public System.DateTime date_created { get; set; }
        public string act_src_lang { get; set; }
        public short voa_version { get; set; }
    }
}
