//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_tr_prjcts
    {
        public string title { get; set; }
        public int status { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.Guid> site_id { get; set; }
        public int retry_count { get; set; }
        public string po_ref { get; set; }
        public Nullable<System.Guid> owner { get; set; }
        public System.Guid id { get; set; }
        public string external_id { get; set; }
        public System.DateTime due_date { get; set; }
        public string dscrptn { get; set; }
        public Nullable<System.DateTime> date_sent { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_completed { get; set; }
        public string cnctr { get; set; }
        public string act_src_lang { get; set; }
    }
}
