//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_user_profile_link
    {
        public string user_profile_type_name { get; set; }
        public Nullable<System.Guid> user_id { get; set; }
        public Nullable<System.Guid> profile_id { get; set; }
        public Nullable<System.Guid> membership { get; set; }
        public System.DateTime last_modified { get; set; }
        public System.Guid id { get; set; }
        public string app_name { get; set; }
    }
}
