//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_url_data
    {
        public string url { get; set; }
        public byte redirect { get; set; }
        public string qery { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public byte is_default { get; set; }
        public System.Guid id { get; set; }
        public byte disabled { get; set; }
        public int culture { get; set; }
        public string app_name { get; set; }
        public short voa_version { get; set; }
        public int voa_class { get; set; }
        public Nullable<System.Guid> content_id { get; set; }
        public Nullable<System.Guid> id2 { get; set; }
        public string item_type { get; set; }
    }
}
