//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_user_profile
    {
        public string url_name_ { get; set; }
        public string title_ { get; set; }
        public string source_key { get; set; }
        public Nullable<System.Guid> user_id { get; set; }
        public System.DateTime last_modified { get; set; }
        public System.Guid id { get; set; }
        public string description_ { get; set; }
        public System.DateTime date_created { get; set; }
        public string app_name { get; set; }
        public int voa_class { get; set; }
    
        public virtual sf_ec_customer_profile sf_ec_customer_profile { get; set; }
        public virtual sf_sitefinity_profile sf_sitefinity_profile { get; set; }
    }
}
