//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_users
    {
        public string user_name { get; set; }
        public string salt { get; set; }
        public string password_question { get; set; }
        public int password_format { get; set; }
        public string password_answer { get; set; }
        public string passwd { get; set; }
        public Nullable<System.Guid> manager_info { get; set; }
        public Nullable<System.DateTime> last_password_changed_date { get; set; }
        public string last_name { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public string last_login_ip { get; set; }
        public Nullable<System.DateTime> last_login_date { get; set; }
        public Nullable<System.DateTime> last_lockout_date { get; set; }
        public Nullable<System.DateTime> last_activity_date { get; set; }
        public Nullable<bool> is_logged_in { get; set; }
        public Nullable<bool> is_locked_out { get; set; }
        public Nullable<bool> is_backend_user { get; set; }
        public Nullable<bool> is_approved { get; set; }
        public System.Guid id { get; set; }
        public string first_name { get; set; }
        public Nullable<System.DateTime> fld_psswrd_ttempt_window_start { get; set; }
        public int failed_password_attempt_count { get; set; }
        public Nullable<System.DateTime> fld_psswrd_nswr_ttmpt_wndw_str { get; set; }
        public int fld_psswrd_nswer_attempt_count { get; set; }
        public string ext_provider_name { get; set; }
        public string ext_id { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string commnt { get; set; }
        public string app_name { get; set; }
    }
}
