//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_vesion_items
    {
        public string type_name { get; set; }
        public Nullable<System.Guid> trunk_id { get; set; }
        public int last_version { get; set; }
        public Nullable<System.Guid> id2 { get; set; }
        public System.DateTime last_modified { get; set; }
        public byte synced { get; set; }
        public System.Guid id { get; set; }
        public string app_name { get; set; }
        public short voa_version { get; set; }
    }
}
