//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_version_chnges
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_version_chnges()
        {
            this.sf_version_dependency = new HashSet<sf_version_dependency>();
        }
    
        public int vrsion { get; set; }
        public Nullable<System.Guid> serial_info_id { get; set; }
        public Nullable<System.Guid> item_id { get; set; }
        public Nullable<System.Guid> ownr { get; set; }
        public string metadata { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public string lbel { get; set; }
        public byte is_published_version { get; set; }
        public System.Guid id { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public byte[] dta { get; set; }
        public int culture { get; set; }
        public string commnt { get; set; }
        public string change_type { get; set; }
        public string app_name { get; set; }
        public string add_info { get; set; }
        public short voa_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_version_dependency> sf_version_dependency { get; set; }
    }
}
