//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_wfl_type_scope
    {
        public Nullable<System.Guid> scope_id { get; set; }
        public System.DateTime last_modified { get; set; }
        public Nullable<byte> include_children { get; set; }
        public System.Guid id { get; set; }
        public string content_type { get; set; }
        public string content_filter { get; set; }
        public string app_name { get; set; }
        public short voa_version { get; set; }
    }
}
