//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_wfl_permission
    {
        public int principal_type { get; set; }
        public string principal_name { get; set; }
        public string principal_id { get; set; }
        public Nullable<System.Guid> workflow_level_id { get; set; }
        public System.DateTime last_modified { get; set; }
        public System.Guid id { get; set; }
        public string app_name { get; set; }
        public string action_name { get; set; }
        public short voa_version { get; set; }
    }
}
