//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_wfl_level
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_wfl_level()
        {
            this.sf_wfl_lvl_cstm_mil_recipients = new HashSet<sf_wfl_lvl_cstm_mil_recipients>();
        }
    
        public float ordinal { get; set; }
        public byte notify_approvers { get; set; }
        public byte notify_administrators { get; set; }
        public System.DateTime last_modified { get; set; }
        public System.Guid id { get; set; }
        public Nullable<System.Guid> workflow_definition_id { get; set; }
        public string app_name { get; set; }
        public string action_name { get; set; }
        public short voa_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_wfl_lvl_cstm_mil_recipients> sf_wfl_lvl_cstm_mil_recipients { get; set; }
    }
}
