//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_wfl_dfntn_prmssnst_bjct_ttl
    {
        public System.Guid id { get; set; }
        public string mapkey { get; set; }
        public string val { get; set; }
    
        public virtual sf_wfl_definition sf_wfl_definition { get; set; }
    }
}
