//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_wfl_definition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sf_wfl_definition()
        {
            this.sf_wfl_dfntn_prmssnst_bjct_ttl = new HashSet<sf_wfl_dfntn_prmssnst_bjct_ttl>();
            this.sf_wfl_dfntn_spprtd_prmssn_sts = new HashSet<sf_wfl_dfntn_spprtd_prmssn_sts>();
            this.sf_permissions = new HashSet<sf_permissions>();
        }
    
        public int workflow_type { get; set; }
        public string title_ { get; set; }
        public Nullable<System.Guid> ownr { get; set; }
        public System.DateTime last_modified { get; set; }
        public byte is_active { get; set; }
        public byte inherits_permissions { get; set; }
        public System.Guid id { get; set; }
        public System.DateTime date_created { get; set; }
        public string custom_xamlx_url { get; set; }
        public byte can_inherit_permissions { get; set; }
        public string application_name { get; set; }
        public byte allw_pblshers_to_skip_workflow { get; set; }
        public Nullable<byte> allow_notes { get; set; }
        public byte allw_dmnstrtrs_t_skip_workflow { get; set; }
        public short voa_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_wfl_dfntn_prmssnst_bjct_ttl> sf_wfl_dfntn_prmssnst_bjct_ttl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_wfl_dfntn_spprtd_prmssn_sts> sf_wfl_dfntn_spprtd_prmssn_sts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sf_permissions> sf_permissions { get; set; }
    }
}
