//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncTask
    {
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public int Priority { get; set; }
        public byte Enabled { get; set; }
        public System.DateTimeOffset FirstExecution { get; set; }
        public Nullable<System.DateTimeOffset> LastExecution { get; set; }
        public Nullable<System.DateTimeOffset> FinalExecution { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTimeOffset> NextExecution { get; set; }
        public int ExecutionCount { get; set; }
        public int Type { get; set; }
        public string RecurrenceRule { get; set; }
        public int FatalityThreshold { get; set; }
        public string ConfigurationId { get; set; }
    }
}
