//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_portal_C_DescEstados
    {
        public int id_aseguradora { get; set; }
        public int id_modelo { get; set; }
        public Nullable<decimal> AGS { get; set; }
        public Nullable<decimal> BCN { get; set; }
        public Nullable<decimal> BCS { get; set; }
        public Nullable<decimal> CAMP { get; set; }
        public Nullable<decimal> CHIS { get; set; }
        public Nullable<decimal> CHIH { get; set; }
        public Nullable<decimal> COAH { get; set; }
        public Nullable<decimal> COL { get; set; }
        public Nullable<decimal> DF { get; set; }
        public Nullable<decimal> DGO { get; set; }
        public Nullable<decimal> EDOMEX { get; set; }
        public Nullable<decimal> GTO { get; set; }
        public Nullable<decimal> GRO { get; set; }
        public Nullable<decimal> HGO { get; set; }
        public Nullable<decimal> JAL { get; set; }
        public Nullable<decimal> NAY { get; set; }
        public Nullable<decimal> NVO_LEON { get; set; }
        public Nullable<decimal> MICH { get; set; }
        public Nullable<decimal> MOR { get; set; }
        public Nullable<decimal> OAX { get; set; }
        public Nullable<decimal> PUE { get; set; }
        public Nullable<decimal> QRO { get; set; }
        public Nullable<decimal> Q_ROO { get; set; }
        public Nullable<decimal> SLP { get; set; }
        public Nullable<decimal> SIN { get; set; }
        public Nullable<decimal> SON { get; set; }
        public Nullable<decimal> TAB { get; set; }
        public Nullable<decimal> TAMPS { get; set; }
        public Nullable<decimal> TLAX { get; set; }
        public Nullable<decimal> VER { get; set; }
        public Nullable<decimal> YUC { get; set; }
        public Nullable<decimal> ZAC { get; set; }
        public Nullable<decimal> BCN_FRONTERA { get; set; }
        public Nullable<decimal> CHIH_FRONTERA { get; set; }
        public Nullable<decimal> NVO_LEON_FRONTERA { get; set; }
        public Nullable<decimal> SON_FRONTERA { get; set; }
        public Nullable<decimal> Q_ROO_FRONTERA { get; set; }
        public Nullable<decimal> TAMPS_FRONTERA { get; set; }
        public Nullable<decimal> BCS_FRONTERA { get; set; }
    }
}
