//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_portal_Distribuidores
    {
        public int IdDealer { get; set; }
        public int IdState { get; set; }
        public string Dealer { get; set; }
        public string Code { get; set; }
        public string Adress { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public bool Status { get; set; }
        public string PostalCode { get; set; }
    }
}
