//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXC.TFSM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_portal_C_DescEstados_V
    {
        public int id_aseguradora { get; set; }
        public int id_modelo { get; set; }
        public string estado { get; set; }
        public Nullable<decimal> valor { get; set; }
    }
}
